# pylint: skip-file
# isort:skip_file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client favorites`

cian-codegen version: 1.9.0

"""
from .offer_favorite_count import OfferFavoriteCount
