# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client favorites`

cian-codegen version: 1.9.0

"""
from dataclasses import dataclass


@dataclass
class OfferFavoriteCount:
    count: int
    offer_id: int
