# pylint: skip-file
# isort:skip_file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client auction`

cian-codegen version: 1.4.3

"""
from .announcements_bet_model import AnnouncementsBetModel
from .announcements_bet_response import AnnouncementsBetResponse
from .get_announcements_bets_request import GetAnnouncementsBetsRequest
