# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client auction`

cian-codegen version: 1.4.3

"""
from dataclasses import dataclass
from typing import Optional

from cian_enum import NoFormat, StrEnum


class AnnouncementCategory(StrEnum):
    __value_format__ = NoFormat
    bed_rent = 'bedRent'
    """Койко-место = 0"""
    building_rent = 'buildingRent'
    """Здание = 1"""
    building_sale = 'buildingSale'
    """Здание = 2"""
    business_rent = 'businessRent'
    """Готовый бизнес = 3"""
    business_sale = 'businessSale'
    """Готовый бизнес = 4"""
    car_service_rent = 'carServiceRent'
    """Аренда автосервис = 5"""
    car_service_sale = 'carServiceSale'
    """Продажа автосервиса = 6"""
    commercial_land_rent = 'commercialLandRent'
    """Коммерческая земля = 7"""
    commercial_land_sale = 'commercialLandSale'
    """Коммерческая земля = 8"""
    cottage_rent = 'cottageRent'
    """Коттедж = 9"""
    cottage_sale = 'cottageSale'
    """Коттедж = 10"""
    daily_bed_rent = 'dailyBedRent'
    """Посуточная аренда койко-места = 11"""
    daily_flat_rent = 'dailyFlatRent'
    """Посуточная аренда квартиры = 12"""
    daily_house_rent = 'dailyHouseRent'
    """Посуточная аренда дома, дачи, коттеджа = 13"""
    daily_room_rent = 'dailyRoomRent'
    """Посуточная аренда комнаты = 14"""
    domestic_services_rent = 'domesticServicesRent'
    """Аренда помещения под бытовые услуги = 15"""
    domestic_services_sale = 'domesticServicesSale'
    """Продажа помещения под бытовые услуги = 16"""
    flat_rent = 'flatRent'
    """Квартира = 17"""
    flat_sale = 'flatSale'
    """Квартира = 18"""
    flat_share_sale = 'flatShareSale'
    """Доля в квартире = 19"""
    free_appointment_object_rent = 'freeAppointmentObjectRent'
    """Помещение свободного назначения = 20"""
    free_appointment_object_sale = 'freeAppointmentObjectSale'
    """Помещение свободного назначения = 21"""
    garage_rent = 'garageRent'
    """Гараж = 22"""
    garage_sale = 'garageSale'
    """Гараж = 23"""
    house_rent = 'houseRent'
    """Дом/дача = 24"""
    house_sale = 'houseSale'
    """Дом/дача = 25"""
    house_share_rent = 'houseShareRent'
    """Часть дома = 26"""
    house_share_sale = 'houseShareSale'
    """Часть дома = 27"""
    industry_rent = 'industryRent'
    """Производство = 28"""
    industry_sale = 'industrySale'
    """Производство = 29"""
    land_sale = 'landSale'
    """Участок = 30"""
    new_building_flat_sale = 'newBuildingFlatSale'
    """Квартира в новостройке = 31"""
    office_rent = 'officeRent'
    """Офис = 32"""
    office_sale = 'officeSale'
    """Офис = 33"""
    public_catering_rent = 'publicCateringRent'
    """Аренда общепита = 34"""
    public_catering_sale = 'publicCateringSale'
    """Продажа общепита = 35"""
    room_rent = 'roomRent'
    """Комната = 36"""
    room_sale = 'roomSale'
    """Комната = 37"""
    shopping_area_rent = 'shoppingAreaRent'
    """Торговая площадь = 38"""
    shopping_area_sale = 'shoppingAreaSale'
    """Торговая площадь = 39"""
    townhouse_rent = 'townhouseRent'
    """Таунхаус = 40"""
    townhouse_sale = 'townhouseSale'
    """Таунхаус = 41"""
    warehouse_rent = 'warehouseRent'
    """Склад = 42"""
    warehouse_sale = 'warehouseSale'
    """Склад = 43"""


@dataclass
class AnnouncementsBetModel:
    """Модель ставки по объявлению"""

    announcement_id: int
    """Id объявления"""
    bet: float
    """Значение ставки"""
    announcement_category: Optional[AnnouncementCategory] = None
    """Категория объявления"""
    county_id: Optional[int] = None
    """Id округа"""
    district_id: Optional[int] = None
    """Id района"""
    is_from_order: Optional[bool] = None
    """Флаг, показывающий установлена ли ставка через xml заказа"""
    region_id: Optional[int] = None
    """Id региона"""
    row_version: Optional[int] = None
    """Версия объявления, к которой применена ставка."""
