# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client auction`

cian-codegen version: 1.9.0

"""
from dataclasses import dataclass

from cian_enum import NoFormat, StrEnum


class Type(StrEnum):
    __value_format__ = NoFormat
    region = 'region'
    """Конкуренция в регионе"""
    local = 'local'
    """Локальная конкуренция"""
    near_by = 'nearBy'
    """Конкуренция по соседству"""


@dataclass
class ConcurrencyTypeModel:
    """Уровень конкуренции"""

    is_active: bool
    """Активная вкладка"""
    name: str
    """Название"""
    type: Type
    """Тип"""
