# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client auction`

cian-codegen version: 1.9.0

"""
from dataclasses import dataclass
from typing import List

from .mobile_bet_announcement_info import MobileBetAnnouncementInfo


@dataclass
class GetMobileBetAnnouncementsInfoResponse:
    """Результат запроса на получение аукционной информации по объявлениям"""

    announcements: List[MobileBetAnnouncementInfo]
    """Аукционная информация по объявлениям"""
