# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client auction`

cian-codegen version: 1.9.0

"""
from dataclasses import dataclass
from typing import List, Optional

from .concurrency_type_model import ConcurrencyTypeModel


@dataclass
class MobileBetAnnouncementInfo:
    """Аукционная информация"""

    announcement_id: int
    """Id объявления"""
    concurrency_type_title: str
    """Название типа конкуренции"""
    concurrency_types: List[ConcurrencyTypeModel]
    """Доступные уровни конкуренции"""
    increase_bets_positions_count: int
    """Объявлений над вами"""
    is_available_auction: bool
    """Доступность для редактирования"""
    serp_position: int
    """Позиция в выдаче"""
    bet_position_info: Optional[str] = None
    """Описание позиции с учетом сквозной конкуренции"""
    current_bet: Optional[int] = None
    """Текущая ставка"""
    is_fixed_bet: Optional[bool] = None
    """Флаг, показывающий, фиксированная ли ставка"""
    is_strategy_enabled: Optional[bool] = None
    """Флаг, показывающий, включена ли стратегия"""
    note_bet: Optional[str] = None
    """Описание ставки"""
    strategy_description: Optional[str] = None
    """Описание стратегии"""
