# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client users`

cian-codegen version: 1.7.1

"""
from dataclasses import dataclass
from typing import List, Optional


@dataclass
class UserIdsRequest:
    """Модель запроса по Realty ID пользователей"""

    user_ids: Optional[List[int]] = None
    """Список Realty ID пользователей"""
