# pylint: skip-file
# isort:skip_file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client offers-duplicates`

cian-codegen version: 1.4.3

"""
from .duplicate import Duplicate
from .offer import Offer
from .get_offers_duplicates_by_ids_request import GetOffersDuplicatesByIdsRequest
from .get_offers_duplicates_by_ids_response import GetOffersDuplicatesByIdsResponse
