# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client offers-duplicates`

cian-codegen version: 1.4.3

"""
from dataclasses import dataclass
from typing import List

from .duplicate import Duplicate


@dataclass
class GetOffersDuplicatesByIdsResponse:
    duplicates: List[Duplicate]
    """Список дубликатов"""
