# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client offers-duplicates`

cian-codegen version: 1.4.3

"""
from dataclasses import dataclass


@dataclass
class Offer:
    id: int
    """Id обьявления"""
    row_version: int
    """Версия обьявления"""
