# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-cian-elasticapi`

cian-codegen version: 1.4.1

"""
from dataclasses import dataclass
from typing import List


@dataclass
class GetApiElasticAnnouncementGet:
    ids: List[int]
