# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-cian-elasticapi`

cian-codegen version: 1.4.1

"""
from dataclasses import dataclass
from datetime import datetime
from typing import Optional


@dataclass
class IElasticAnnouncement:
    realty_object_id: Optional[int] = None
    """ID объявления"""
    row_version: Optional[int] = None
    """Версия объявления"""
    object_model: Optional[str] = None
    """JSON с данными объявления"""
