# pylint: skip-file
"""

Code generated by new-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client announcementapi`

new-codegen version: 4.0.0

"""
from typing import Callable

from cian_automation.context import LazyImport
from cian_automation.web import DecoratedBaseClient
from .. import entities


class V2AnnouncementsAdd(DecoratedBaseClient):
    _is_service = True
    microservice_name = 'announcementapi'
    path = '/v2/announcements/add/'
    path_args = []
    responses = {'post': entities.AddObjectResult}
    request_post: Callable[..., 'entities.AddObjectResult']
