# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client moderation-checks-orchestrator`

cian-codegen version: 1.9.0

"""
from ._repo import v1_check_users_need_identification
