# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client moderation-checks-orchestrator`

cian-codegen version: 1.9.0

"""
from typing import List

from cian_http.api_client import Api

from . import entities


_api = Api(microservice_name='moderation-checks-orchestrator')
v1_check_users_need_identification = _api.make_client(
    path='/v1/check-users-need-identification/',
    method='POST',
    handle_http_exceptions=True,
    request_schema=entities.CheckUsersNeedIdentificationRequest,
    response_schema=List[entities.UserIdentificationResult],
)
