# pylint: skip-file
# isort:skip_file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-cian-realty`

cian-codegen version: 1.4.1

"""
from .bounded_by_corner import BoundedByCorner
from .bounded_by import BoundedBy
from .get_regions_response import GetRegionsResponse
