# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-cian-realty`

cian-codegen version: 1.4.3

"""
from dataclasses import dataclass
from datetime import datetime
from typing import Optional


@dataclass
class ApiCurrencies:
    date: Optional[datetime] = None
