# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-cian-realty`

cian-codegen version: 1.4.3

"""
from dataclasses import dataclass
from datetime import datetime
from typing import Optional


@dataclass
class Currency:
    """Валюта и её курс за определённую дату."""

    currency_code: Optional[str] = None
    """Код валюты."""
    date: Optional[datetime] = None
    """Дата курса."""
    rate: Optional[float] = None
    """Курс."""
