# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-cian-realty`

cian-codegen version: 1.4.3

"""
from dataclasses import dataclass
from datetime import datetime
from typing import Optional

from cian_enum import NoFormat, StrEnum


class BroadcastType(StrEnum):
    __value_format__ = NoFormat
    temp = 'temp'
    """Отсылать в темповый Exchange"""
    all = 'all'
    """Рассылать в боевой Exchange"""


class State(StrEnum):
    __value_format__ = NoFormat
    active = 'active'
    """Активный"""
    finished = 'finished'
    """Завершенный"""
    finished_with_errors = 'finishedWithErrors'
    """Завершенный с ошибками"""


class Type(StrEnum):
    __value_format__ = NoFormat
    announcement = 'announcement'
    """Объявление"""
    users = 'users'
    """Пользователь"""
    agent = 'agent'
    """Агент"""


@dataclass
class GetResendMessagesJobResponse:
    """Ответ на получение статуса задачи на переотправку сообщений"""

    broadcast_type: Optional[BroadcastType] = None
    """Тип отправки"""
    comment: Optional[str] = None
    """Комментарий"""
    creation_date: Optional[datetime] = None
    """Дата создания"""
    data: Optional[dict] = None
    """Данные"""
    state: Optional[State] = None
    """Состояние"""
    type: Optional[Type] = None
    """Тип"""
