# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-cian-realty`

cian-codegen version: 1.4.3

"""
from dataclasses import dataclass
from typing import List

from cian_enum import NoFormat, StrEnum


class BroadcastType(StrEnum):
    __value_format__ = NoFormat
    temp = 'temp'
    """Отсылать в темповый Exchange"""
    all = 'all'
    """Рассылать в боевой Exchange"""


@dataclass
class ResendAnnouncementsMessagesRequest:
    """Запрос на переотправку сообщений по объявлениям"""

    broadcast_type: BroadcastType
    """Тип отправки"""
    comment: str
    """Комментарий"""
    ids: List[int]
    """Список id объявлений"""
