# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-cian-realty`

cian-codegen version: 1.4.3

"""
from dataclasses import dataclass


@dataclass
class ResendReportingMessagesResponse:
    """Ответ на запрос переотправки сообщений"""

    id: int
    """Id задачи"""
