# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client agencies-settings`

cian-codegen version: 1.4.2

"""
from cian_http.api_client import Api

from . import entities


_api = Api(microservice_name='agencies-settings')
v1_get_settings = _api.make_client(
    path='/v1/get-settings/',
    method='GET',
    handle_http_exceptions=True,
    request_schema=entities.V1GetSettings,
    response_schema=entities.AgencySettings,
)
