# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-cian-realty`

cian-codegen version: 1.4.1

"""
from ._repo import api_announcement_set_deleted, api_geo_get_regions
