# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-cian-realty`

cian-codegen version: 1.4.1

"""
from typing import List

from cian_http.api_client import Api

from . import entities


_api = Api(microservice_name='monolith-cian-realty')
api_geo_get_regions = _api.make_client(
    path='/api/geo/get-regions/',
    method='GET',
    handle_http_exceptions=True,
    response_schema=List[entities.GetRegionsResponse],
)
