# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-cian-realty`

cian-codegen version: 1.4.1

"""
from typing import List

from cian_http.api_client import Api

from . import entities


_api = Api(microservice_name='monolith-cian-realty')
api_announcement_set_deleted = _api.make_client(
    path='/api/announcement/set-deleted/',
    method='POST',
    handle_http_exceptions=True,
    request_schema=entities.AnnouncementChangeStatus,
)
api_geo_get_regions = _api.make_client(
    path='/api/geo/get-regions/',
    method='GET',
    handle_http_exceptions=True,
    response_schema=List[entities.GetRegionsResponse],
)
api_v1_resend_reporting_messages_get_job = _api.make_client(
    path='/api/v1/resend-reporting-messages/get-job/',
    method='GET',
    handle_http_exceptions=True,
    request_schema=entities.ApiV1ResendReportingMessagesGetJob,
    response_schema=entities.GetResendMessagesJobResponse,
)
api_v1_resend_reporting_messages_resend_announcements = _api.make_client(
    path='/api/v1/resend-reporting-messages/resend-announcements/',
    method='POST',
    handle_http_exceptions=True,
    request_schema=entities.ResendAnnouncementsMessagesRequest,
    response_schema=entities.ResendReportingMessagesResponse,
)
