# pylint: skip-file
"""

Code generated by new-codegen; DO NOT EDIT.

To re-generate, run `new-codegen generate-client my-offers`

new-codegen version: 4.0.2

"""
from dataclasses import dataclass

from cian_enum import NoFormat, StrEnum


class Type(StrEnum):
    __value_format__ = NoFormat
    country = 'country'
    """Страна"""
    district = 'district'
    """Район"""
    house = 'house'
    """Дом"""
    location = 'location'
    """Местоположение"""
    road = 'road'
    """Шоссе"""
    street = 'street'
    """Улица"""


@dataclass
class Address:
    name: str
    """Полный адрес"""
    searchUrl: str
    """Поисковый запрос по адресу"""
    type: Type
    """Тип элемента адреса"""
