# pylint: skip-file
"""

Code generated by new-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client my-offers`

new-codegen version: 4.0.0

"""
from dataclasses import dataclass


@dataclass
class Address:
    name: str
    """Полный адрес"""
    url: str
    """Поисковый запрос по адресу"""
