# pylint: skip-file
"""

Code generated by new-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client my-offers`

new-codegen version: 4.0.1

"""
from dataclasses import dataclass
from typing import Optional


@dataclass
class Auction:
    bet: Optional[int] = None
    """Текущая ставка аукциона"""
    districtPlace: Optional[int] = None
    """Позиция конкуренции по району"""
    homePlace: Optional[int] = None
    """Позиция конкуренции по дому"""
