# pylint: skip-file
"""

Code generated by new-codegen; DO NOT EDIT.

To re-generate, run `new-codegen generate-client my-offers`

new-codegen version: 4.0.2

"""
from dataclasses import dataclass


@dataclass
class AvailableActions:
    canDelete: bool
    """Можно ли удалить объялвение"""
    canEdit: bool
    """Можно редактировать"""
    canMoveToArchive: bool
    """Пользователь может перенести объявление в архив"""
    canRaise: bool
    """Можно ли поднять в размещении"""
    canRestore: bool
    """Можно восстановить"""
    canUpdateEditDate: bool
    """Можно обновить дату"""
