# pylint: skip-file
"""

Code generated by new-codegen; DO NOT EDIT.

To re-generate, run `new-codegen generate-client my-offers`

new-codegen version: 4.0.2

"""
from dataclasses import dataclass
from datetime import datetime
from typing import List, Optional

from .available_actions import AvailableActions
from .offer_geo import OfferGeo
from .page_specific_info import PageSpecificInfo
from .price_info import PriceInfo
from .statistics import Statistics
from .subagent import Subagent


@dataclass
class GetOfferV2:
    availableActions: AvailableActions
    """Доступные действия с объявлениями"""
    features: List[str]
    """Ключевые параметры: комиссии, бонусы, свободная продажа, ипотека"""
    geo: OfferGeo
    """Гео"""
    id: int
    """ID объявления"""
    isManual: bool
    """ Флаг 'из импорта'"""
    pageSpecificInfo: PageSpecificInfo
    """Данные зависящие от конкретной вкладки"""
    priceInfo: PriceInfo
    """Инофрмация о цене"""
    url: str
    """URL объявления"""
    archivedAt: Optional[datetime] = None
    """Дата архивации"""
    createdAt: Optional[datetime] = None
    """Дата подачи объявления"""
    displayDate: Optional[datetime] = None
    """Дата для отображения в карточке"""
    mainPhotoUrl: Optional[str] = None
    """Основаная фотография объекта"""
    statistics: Optional[Statistics] = None
    """Статистика по объявлению"""
    status: Optional[str] = None
    """Строка статуса"""
    subagent: Optional[Subagent] = None
    """Сабагент"""
    title: Optional[str] = None
    """Заголовок объявления"""
