# pylint: skip-file
"""

Code generated by new-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client my-offers`

new-codegen version: 4.0.1

"""
from dataclasses import dataclass
from datetime import datetime
from typing import List, Optional

from cian_enum import NoFormat, StrEnum

from .auction import Auction
from .available_actions import AvailableActions
from .offer_geo import OfferGeo
from .price_info import PriceInfo
from .statistics import Statistics
from .subagent import Subagent


class Vas(StrEnum):
    __value_format__ = NoFormat
    auction = 'auction'
    colorized = 'colorized'
    payed = 'payed'
    premium = 'premium'
    top3 = 'top3'


@dataclass
class GetOffer:
    availableActions: AvailableActions
    """Доступные действия с объявлениями"""
    createdAt: datetime
    """Дата подачи объявления"""
    features: List[str]
    """Ключевые параметры: комиссии, бонусы, свободная продажа, ипотека"""
    geo: OfferGeo
    """Гео"""
    id: int
    """ID объявления"""
    isFromPackage: bool
    """ Флаг 'из пакета'"""
    isManual: bool
    """ Флаг 'из импорта'"""
    isPublicationTimeEnds: bool
    """ Флаг 'меньше суток до конца публикации'"""
    priceInfo: PriceInfo
    """Инофрмация о цене"""
    url: str
    """URL объявления"""
    vas: List[Vas]
    """Список VAS'ов"""
    archivedAt: Optional[datetime] = None
    """Дата архивации"""
    auction: Optional[Auction] = None
    """Данные об аукционе по объявлению"""
    mainPhotoUrl: Optional[str] = None
    """Основаная фотография объекта"""
    publishFeatures: Optional[List[str]] = None
    """Параметры публикации: сколько осталось, автопродление"""
    statistics: Optional[Statistics] = None
    """Статистика по объявлению"""
    status: Optional[str] = None
    """Строка статуса"""
    subagent: Optional[Subagent] = None
    """Сабагент"""
    title: Optional[str] = None
    """Заголовок объявления"""
