# pylint: skip-file
"""

Code generated by new-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client my-offers`

new-codegen version: 4.0.0

"""
from dataclasses import dataclass
from typing import List

from .get_offer import GetOffer
from .offer_counters import OfferCounters
from .page_info import PageInfo


@dataclass
class GetOffersResponse:
    counters: OfferCounters
    offers: List[GetOffer]
    page: PageInfo
