# pylint: skip-file
"""

Code generated by new-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client my-offers`

new-codegen version: 4.0.0

"""
from dataclasses import dataclass
from datetime import datetime
from typing import List, Optional

from cian_enum import NoFormat, StrEnum

from .auction import Auction
from .offer_geo import OfferGeo
from .price_info import PriceInfo
from .statistics import Statistics
from .subagent import Subagent


class Vas(StrEnum):
    __value_format__ = NoFormat
    auction = 'auction'
    calltracking = 'calltracking'
    free = 'free'
    highlight = 'highlight'
    paid = 'paid'
    premium = 'premium'
    top3 = 'top3'


@dataclass
class GetOffer:
    features: List[str]
    """Ключевые параметры: комиссии, бонусы, свободная продажа, ипотека"""
    isFromImport: bool
    """ Флаг 'из импорта'
    """
    isFromPackage: bool
    """ Флаг 'из пакета'
    """
    isPublicationTimeEnds: bool
    """ Флаг 'меньше суток до конца публикации'
    """
    priceInfo: PriceInfo
    """Инофрмация о цене"""
    auction: Optional[Auction] = None
    """Данные об аукционе по объявлению"""
    createdAt: Optional[datetime] = None
    """Дата подачи объявления"""
    geo: Optional[OfferGeo] = None
    """Гео"""
    id: Optional[int] = None
    """ID объявления"""
    mainPhotoUrl: Optional[str] = None
    """Основаная фотография объекта"""
    publishFeatures: Optional[List[str]] = None
    """Параметры публикации: сколько осталось, автопродление"""
    statistics: Optional[Statistics] = None
    """Статистика по объявлению"""
    subagent: Optional[Subagent] = None
    """Сабагент"""
    title: Optional[str] = None
    """Заголовок объявления"""
    url: Optional[str] = None
    """URL объявления"""
    vas: Optional[List[Vas]] = None
    """Список VAS'ов"""
