# pylint: skip-file
"""

Code generated by new-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client my-offers`

new-codegen version: 4.0.0

"""
from dataclasses import dataclass
from typing import Optional

from cian_enum import NoFormat, StrEnum

from .filter import Filter
from .pagination import Pagination


class Sort(StrEnum):
    __value_format__ = NoFormat
    by_area_max = 'byAreaMax'
    """По площади: возрастающая"""
    by_area_min = 'byAreaMin'
    """По площади: убывающая"""
    by_offer_id = 'byOfferId'
    """По ID объявления"""
    by_price_for_meter = 'byPriceForMeter'
    """По цене за метр"""
    by_price_max = 'byPriceMax'
    """По цене: возрастающая"""
    by_price_min = 'byPriceMin'
    """По цене: убывающая"""
    by_street = 'byStreet'
    """По улице"""
    by_walk_time = 'byWalkTime'
    """По времени до метро"""


@dataclass
class GetOffersRequest:
    filters: Filter
    """Параметры фильтрации"""
    pagination: Optional[Pagination] = None
    """Параметры страницы"""
    sort: Optional[Sort] = None
    """Сортировка"""
