# pylint: skip-file
"""

Code generated by new-codegen; DO NOT EDIT.

To re-generate, run `new-codegen generate-client my-offers`

new-codegen version: 4.0.2

"""
from dataclasses import dataclass
from datetime import datetime
from typing import Optional


@dataclass
class Moderation:
    declinedDate: Optional[datetime] = None
    """Дата отклонения"""
    isDeclined: Optional[bool] = None
    """Отклонено ли модератором"""
    offenceStatus: Optional[str] = None
    """Статус модерации"""
    reason: Optional[str] = None
    """Текст причины отклонения"""
