# pylint: skip-file
"""

Code generated by new-codegen; DO NOT EDIT.

To re-generate, run `new-codegen generate-client my-offers`

new-codegen version: 4.0.2

"""
from dataclasses import dataclass
from typing import Optional


@dataclass
class NotActiveInfo:
    status: str
    """Статус для некативных"""
    message: Optional[str] = None
    """Доп. сообщение"""
