# pylint: skip-file
"""

Code generated by new-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client my-offers`

new-codegen version: 4.0.1

"""
from dataclasses import dataclass


@dataclass
class OfferActionRequest:
    offerId: int
