# pylint: skip-file
"""

Code generated by new-codegen; DO NOT EDIT.

To re-generate, run `new-codegen generate-client my-offers`

new-codegen version: 4.0.2

"""
from dataclasses import dataclass
from typing import Optional


@dataclass
class OfferCounters:
    active: Optional[int] = None
    archived: Optional[int] = None
    declined: Optional[int] = None
    notActive: Optional[int] = None
