# pylint: skip-file
"""

Code generated by new-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client my-offers`

new-codegen version: 4.0.0

"""
from dataclasses import dataclass
from typing import Optional

from .address import Address
from .newbuilding import Newbuilding
from .underground import Underground


@dataclass
class OfferGeo:
    address: Optional[Address] = None
    """Адрес"""
    newbuilding: Optional[Newbuilding] = None
    """Новостройки"""
    underground: Optional[Underground] = None
    """Метро"""
