# pylint: skip-file
"""

Code generated by new-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client my-offers`

new-codegen version: 4.0.1

"""
from dataclasses import dataclass
from typing import List, Optional


@dataclass
class PriceInfo:
    exact: Optional[str] = None
    """Цена"""
    range: Optional[List[str]] = None
    """Диапазон цен"""
