# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client price-estimator`

cian-codegen version: 1.4.3

"""
from dataclasses import dataclass
from typing import Optional

from .liquidity_periods_range import LiquidityPeriodsRange
from .price_with_range import PriceWithRange


@dataclass
class GetEstimationForRealtorsResponse:
    liquidity_periods: Optional[LiquidityPeriodsRange] = None
    """Объект с ликвидностью"""
    prices: Optional[PriceWithRange] = None
    """Объект с оценкой и её диапазоном"""
    url: Optional[str] = None
    """Ссылка на результаты оценки калькулятора недвижимости"""
