# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client price-estimator`

cian-codegen version: 1.4.3

"""
from dataclasses import dataclass
from typing import Optional


@dataclass
class LiquidityTermRange:
    min_selling_term: int
    """Минимальный срок продажи, в днях"""
    max_selling_term: Optional[int] = None
    """Максимальный срок продажи, в днях"""
