# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client price-estimator`

cian-codegen version: 1.4.3

"""
from dataclasses import dataclass

from .liquidity_term_range import LiquidityTermRange


@dataclass
class LiquidityPeriodsRange:
    period_with_promotion: LiquidityTermRange
    """Срок продажи квартиры "от-до" в днях при текущей цене с продвижением"""
    regular_period: LiquidityTermRange
    """Срок продажи квартиры "от-до" в днях при текущей цене и без продвижения"""
