# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client price-estimator`

cian-codegen version: 1.4.3

"""
from dataclasses import dataclass
from typing import Optional


@dataclass
class PriceWithRange:
    price: Optional[int] = None
    """Цена (аренда/продажа) в этом доме(с учётом метража)"""
    price_max: Optional[int] = None
    """Максимальная цена (аренда/продажа) в этом доме(с учётом метража)"""
    price_min: Optional[int] = None
    """Минимальная цена (аренда/продажа) в этом доме(с учётом метража)"""
