# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client price-estimator`

cian-codegen version: 1.4.3

"""
from dataclasses import dataclass


@dataclass
class V2GetEstimationForRealtors:
    realty_offer_id: int
    """realty ID объявления"""
