# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client agents`

cian-codegen version: 1.15.0

"""
from ._repo import v1_get_agencies_with_activated_staff_service, v1_get_agents_list
