# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client agents`

cian-codegen version: 1.15.0

"""
from cian_http.api_client import Api

from . import entities

_api = Api(microservice_name='agents')
v1_get_agencies_with_activated_staff_service = _api.make_client(
    path='/v1/get-agencies-with-activated-staff-service/',
    method='GET',
    handle_http_exceptions=True,
    response_schema=entities.GetAgenciesWithActivatedStaffServiceResponse,
)
v1_get_agents_list = _api.make_client(
    path='/v1/get-agents-list/',
    method='GET',
    handle_http_exceptions=True,
    request_schema=entities.V1GetAgentsList,
    response_schema=entities.AgentsListResponse,
)
