# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-cian-announcementapi`

cian-codegen version: 1.4.1

"""
from dataclasses import dataclass
from typing import Optional

from cian_enum import NoFormat, StrEnum


class Type(StrEnum):
    __value_format__ = NoFormat
    country = 'country'
    """Страна"""
    district = 'district'
    """Район"""
    house = 'house'
    """Дом"""
    location = 'location'
    """Местоположение"""
    road = 'road'
    """Шоссе"""
    street = 'street'
    """Улица"""
    underground = 'underground'
    """Метро"""


@dataclass
class AddressInfo:
    """Адрес"""

    full_name: Optional[str] = None
    """Полное название"""
    id: Optional[int] = None
    """ID гео-привязки"""
    is_forming_address: Optional[bool] = None
    """Участвует в образовании адреса"""
    location_type_id: Optional[int] = None
    """ID типа субъекта"""
    name: Optional[str] = None
    """Название"""
    short_name: Optional[str] = None
    """Короткое название"""
    type: Optional[Type] = None
    """Тип гео-привязки"""
