# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-cian-announcementapi`

cian-codegen version: 1.5.0

"""
from dataclasses import dataclass


@dataclass
class AnnouncementsActionsV1GetJobStatus:
    job_id: int
    """Id задачи"""
    user_id: int
    """Realty id пользователя"""
