# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-cian-announcementapi`

cian-codegen version: 1.5.0

"""
from dataclasses import dataclass
from typing import Optional

from cian_enum import NoFormat, StrEnum


class State(StrEnum):
    __value_format__ = NoFormat
    new = 'New'
    """Новое"""
    in_progress = 'InProgress'
    """В обработке"""
    completed = 'Completed'
    """Завершено"""
    error = 'Error'
    """Завершено с ошибками"""


@dataclass
class AnnouncementProgressDto:
    """Результат обработки объявления."""

    error_key: Optional[str] = None
    """Ключ ошибки."""
    error_message: Optional[str] = None
    """Сообщение об ошибке."""
    id: Optional[int] = None
    """ID объявления."""
    state: Optional[State] = None
    """Статус обработки."""
