# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-cian-announcementapi`

cian-codegen version: 1.5.0

"""
from dataclasses import dataclass
from typing import List


@dataclass
class ChangeOwnerRequest:
    """Запрос на создание задачи массового восстановления"""

    actor_id: int
    """Realty id инициатора смены владельца объявлений"""
    announcement_ids: List[int]
    """Список id объявлений"""
    new_owner_id: int
    """Realty id нового владельца объявлений"""
