# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-cian-announcementapi`

cian-codegen version: 1.5.0

"""
from dataclasses import dataclass
from typing import Optional


@dataclass
class CommercialBuildingInfrastructure:
    """Инфраструктура"""

    has_aquapark: Optional[bool] = None
    """Аквапарк"""
    has_atm: Optional[bool] = None
    """Банкомат"""
    has_automatic_gates: Optional[bool] = None
    """Автоматические ворота"""
    has_baby_sitting: Optional[bool] = None
    """Беби-ситинг"""
    has_bank_department: Optional[bool] = None
    """Отделение банка"""
    has_basement: Optional[bool] = None
    """Подвал/погреб"""
    has_beauty_shop: Optional[bool] = None
    """Салон красоты"""
    has_bowling: Optional[bool] = None
    """Боулинг"""
    has_buffet: Optional[bool] = None
    """Буфет"""
    has_cafe: Optional[bool] = None
    """Кафе"""
    has_canteen: Optional[bool] = None
    """Столовая"""
    has_car_service: Optional[bool] = None
    """Автосервис"""
    has_car_wash: Optional[bool] = None
    """Автомойка"""
    has_central_reception: Optional[bool] = None
    """Центральная рецепция"""
    has_cinema: Optional[bool] = None
    """Кинотеатр"""
    has_clothes_studio: Optional[bool] = None
    """Ателье одежды"""
    has_conference_room: Optional[bool] = None
    """Конференц-зал"""
    has_entry_by_pass: Optional[bool] = None
    """Въезд по пропускам"""
    has_exhibition_and_warehouse_complex: Optional[bool] = None
    """Выставочно-складской комплекс"""
    has_fitness_centre: Optional[bool] = None
    """Фитнес-центр"""
    has_food_court: Optional[bool] = None
    """Фуд-корт"""
    has_game_room: Optional[bool] = None
    """Игровая комната"""
    has_hotel: Optional[bool] = None
    """Гостиница"""
    has_hour_security: Optional[bool] = None
    """Круглосуточная охрана"""
    has_inspection_pit: Optional[bool] = None
    """Смотровая яма"""
    has_medical_center: Optional[bool] = None
    """Медицинский центр"""
    has_minimarket: Optional[bool] = None
    """Минимаркет"""
    has_notary_office: Optional[bool] = None
    """Нотариальная контора"""
    has_office_space: Optional[bool] = None
    """Офисные помещения"""
    has_park: Optional[bool] = None
    """Парк"""
    has_pharmacy: Optional[bool] = None
    """Аптека"""
    has_pool: Optional[bool] = None
    """Бассейн"""
    has_restaurant: Optional[bool] = None
    """Ресторан"""
    has_rink: Optional[bool] = None
    """Каток"""
    has_shopping_area: Optional[bool] = None
    """Торговая зона"""
    has_slot_machines: Optional[bool] = None
    """Игровые автоматы"""
    has_studio: Optional[bool] = None
    """Фотосалон"""
    has_supermarket: Optional[bool] = None
    """Супермаркет"""
    has_tire: Optional[bool] = None
    """Шиномонтаж"""
    has_video_surveillance: Optional[bool] = None
    """Видеонаблюдение"""
    has_warehouse: Optional[bool] = None
    """Складские помещения"""
