# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-cian-announcementapi`

cian-codegen version: 1.15.0

"""
from dataclasses import dataclass
from typing import List, Optional

from cian_enum import NoFormat, StrEnum

from .work_time import WorkTime


class AccessType(StrEnum):
    __value_format__ = NoFormat
    weekdays = 'weekdays'
    """С понедельника по пятницу"""
    daily = 'daily'
    """Ежедневно"""


class Amenities(StrEnum):
    __value_format__ = NoFormat
    wifi = 'wifi'
    bike_parking = 'bikeParking'
    internet = 'internet'
    rest_zone = 'restZone'
    cafe = 'cafe'
    cleaning = 'cleaning'
    kitchen = 'kitchen'
    furniture = 'furniture'
    security = 'security'
    parking = 'parking'
    meeting_room = 'meetingRoom'
    printer = 'printer'
    reception = 'reception'
    modern = 'modern'
    gym = 'gym'
    phone_booth = 'phoneBooth'
    tech_support = 'techSupport'
    events = 'events'
    fax = 'fax'
    flipchart = 'flipchart'
    fruits = 'fruits'
    tea = 'tea'
    lockers = 'lockers'
    legal_address = 'legalAddress'
    microphone = 'microphone'
    sound_absorbing_panels = 'soundAbsorbingPanels'
    projector = 'projector'


@dataclass
class Coworking:
    """Коворкинг"""

    access_type: Optional[AccessType] = None
    """Доступ"""
    amenities: Optional[List[Amenities]] = None
    """Удобства"""
    id: Optional[int] = None
    """ID коворкинга в базе мкс coworking"""
    is_round_the_clock: Optional[bool] = None
    """Работает круглосуточно"""
    name: Optional[str] = None
    """Название коворкинга."""
    work_time: Optional[WorkTime] = None
    """Рабочее время"""
