# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-cian-announcementapi`

cian-codegen version: 1.4.1

"""
from dataclasses import dataclass
from typing import Optional

from cian_enum import NoFormat, StrEnum


class PersonType(StrEnum):
    __value_format__ = NoFormat
    natural = 'natural'
    """Физическое лицо"""
    legal = 'legal'
    """Юридическое лицо"""


@dataclass
class CplModeration:
    """Информация о CPL модерации"""

    first_name: Optional[str] = None
    """Имя (для физ. лица)"""
    inn: Optional[str] = None
    """ИНН (для юр. лица)"""
    last_name: Optional[str] = None
    """Фамилия (для физ. лица)"""
    person_type: Optional[PersonType] = None
    """Тип лица"""
    second_name: Optional[str] = None
    """Отчество (для физ. лица)"""
