# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-cian-announcementapi`

cian-codegen version: 1.5.0

"""
from dataclasses import dataclass
from typing import Optional

from cian_enum import NoFormat, StrEnum


class Type(StrEnum):
    __value_format__ = NoFormat
    beam = 'beam'
    """Кран-балка"""
    gantry = 'gantry'
    """Козловой кран"""
    overhead = 'overhead'
    """Мостовой кран"""
    railway = 'railway'
    """Ж/д кран"""


@dataclass
class CranageType:
    """Крановое оборудование"""

    count: Optional[int] = None
    """Количество"""
    load_capacity: Optional[int] = None
    """Грузоподъёмность"""
    type: Optional[Type] = None
    """Тип кранового оборудования"""
