# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-cian-announcementapi`

cian-codegen version: 1.9.0

"""
from dataclasses import dataclass
from typing import Optional

from cian_enum import NoFormat, StrEnum


class LocationType(StrEnum):
    __value_format__ = NoFormat
    no = 'no'
    """Нет"""
    border = 'border'
    """По границе участка"""
    location = 'location'
    """На участке"""


class Type(StrEnum):
    __value_format__ = NoFormat
    autonomous = 'autonomous'
    """Автономная"""
    central = 'central'
    """Центральная"""
    septic_tank = 'septicTank'
    """Септик"""
    storm = 'storm'
    """Ливневая"""
    treatment_facilities = 'treatmentFacilities'
    """Очистные сооружения"""


@dataclass
class Drainage:
    """Канализация"""

    capacity: Optional[int] = None
    """Объём, м³/сутки"""
    location_type: Optional[LocationType] = None
    """Локация канализации"""
    possible_to_connect: Optional[bool] = None
    """Возможно подключить"""
    type: Optional[Type] = None
    """Тип канализации"""
