# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-cian-announcementapi`

cian-codegen version: 1.15.0

"""
from dataclasses import dataclass
from typing import Optional

from cian_enum import NoFormat, StrEnum


class IdentificationPersonType(StrEnum):
    __value_format__ = NoFormat
    natural = 'natural'
    """Физическое лицо"""
    ip = 'ip'
    """ИП"""
    legal = 'legal'
    """Юридическое лицо"""


@dataclass
class HomeOwner:
    """Информация о собственнике"""

    cadastral_number: Optional[str] = None
    """Кадастровый номер"""
    first_name: Optional[str] = None
    """Имя собственника"""
    flat_number: Optional[str] = None
    """Номер квартиры"""
    house_number: Optional[str] = None
    """Номер дома"""
    identification_person_type: Optional[IdentificationPersonType] = None
    """Идентификация персонального лица."""
    inn: Optional[str] = None
    """ИНН (для юр. лица или ИП)."""
    last_name: Optional[str] = None
    """Фамилия собственника"""
    second_name: Optional[str] = None
    """Отчетство собственника"""
