# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-cian-announcementapi`

cian-codegen version: 1.9.0

"""
from dataclasses import dataclass
from typing import Optional


@dataclass
class HomeOwner:
    """Информация о собственнике"""

    cadastral_number: Optional[str] = None
    """Кадастровый номер"""
    first_name: Optional[str] = None
    """Имя собственника"""
    flat_number: Optional[str] = None
    """Номер квартиры"""
    house_number: Optional[str] = None
    """Номер дома"""
    last_name: Optional[str] = None
    """Фамилия собственника"""
    second_name: Optional[str] = None
    """Отчетство собственника"""
