# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-cian-announcementapi`

cian-codegen version: 1.5.0

"""
from dataclasses import dataclass
from typing import Optional


@dataclass
class Kp:
    """КП"""

    id: Optional[int] = None
    'ID коттеджного посёлка в базе CIAN<br />\r\nИдентификатор можно получить из url карточки коттеджного посёлка:<br /><img src="https://files.cian.ru/files/images/xml_import/doc_kpschema_id.png" width="415px" />'
    is_resale: Optional[bool] = None
    """Признак вторичной недвижимости в КП"""
