# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-cian-announcementapi`

cian-codegen version: 1.4.1

"""
from dataclasses import dataclass
from typing import List, Optional


@dataclass
class LocationPath:
    """LocationPath"""

    child_to_parent: Optional[List[int]] = None
    """Список локаций отсортированный от более детализированного к региону"""
    country_id: Optional[int] = None
    """ID страны"""
