# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-cian-announcementapi`

cian-codegen version: 1.9.0

"""
from dataclasses import dataclass
from typing import Optional

from cian_enum import NoFormat, StrEnum


class Currency(StrEnum):
    __value_format__ = NoFormat
    eur = 'eur'
    """Евро"""
    rur = 'rur'
    """Рубль"""
    usd = 'usd'
    """Доллар"""


class LocationType(StrEnum):
    __value_format__ = NoFormat
    external = 'external'
    """За территорией объекта"""
    internal = 'internal'
    """На территории объекта"""


class PurposeType(StrEnum):
    __value_format__ = NoFormat
    cargo = 'cargo'
    """Для грузового транспорта"""
    passenger = 'passenger'
    """Для легковесного транспорта"""


class Type(StrEnum):
    __value_format__ = NoFormat
    ground = 'ground'
    """Наземная"""
    multilevel = 'multilevel'
    """Многоуровневая"""
    roof = 'roof'
    """На крыше"""
    underground = 'underground'
    """Подземная"""
    open = 'open'
    """Открытая"""


@dataclass
class Parking:
    """Парковка"""

    currency: Optional[Currency] = None
    """Валюта"""
    is_available: Optional[bool] = None
    """Доступна"""
    is_free: Optional[bool] = None
    """Бесплатная"""
    location_type: Optional[LocationType] = None
    """Расположение парковки"""
    places_count: Optional[int] = None
    """Количество мест"""
    price_entry: Optional[float] = None
    """Стоимость въезда"""
    price_monthly: Optional[float] = None
    """Стоимость в месяц за место"""
    purpose_type: Optional[PurposeType] = None
    """Назначение парковки"""
    type: Optional[Type] = None
    """Тип парковки"""
