# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-cian-announcementapi`

cian-codegen version: 1.4.1

"""
from dataclasses import dataclass
from typing import Optional

from .source_phone import SourcePhone


@dataclass
class Phone:
    country_code: str
    """Код страны"""
    number: str
    """Номер"""
    source_phone: Optional[SourcePhone] = None
    """Исходный номер телефона"""
