# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-cian-announcementapi`

cian-codegen version: 1.15.0

"""
from dataclasses import dataclass
from typing import Optional

from cian_enum import NoFormat, StrEnum


class ExternalSource(StrEnum):
    __value_format__ = NoFormat
    emls = 'emls'
    """ЕМЛС"""
    sub_agents = 'subAgents'
    """Субагенты"""
    n1 = 'n1'
    """N1"""
    mlsn = 'mlsn'
    """N1"""


class Type(StrEnum):
    __value_format__ = NoFormat
    web_site = 'webSite'
    android = 'android'
    ios = 'ios'
    upload = 'upload'
    app = 'app'
    qa_autotests = 'qaAutotests'


@dataclass
class Platform:
    external_id: Optional[str] = None
    """Внешний id объявления"""
    external_source: Optional[ExternalSource] = None
    type: Optional[Type] = None
    version: Optional[str] = None
