# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-cian-announcementapi`

cian-codegen version: 1.9.0

"""
from dataclasses import dataclass
from typing import List, Optional

from .publish_term import PublishTerm


@dataclass
class PublishTerms:
    """Условия размещения объявления"""

    autoprolong: Optional[bool] = None
    """Автопродление включено"""
    infinite_publish_period: Optional[bool] = None
    'Если true, то будет использован бесконечный период публикации.\r\nТолько для выгрузок, при ручной подаче игнорируем.'
    skip_billing: Optional[bool] = None
    'Пропускает биллинг объявления.\r\nТолько для выгрузок, при ручной подаче игнорируем.'
    skip_minimal_price_check: Optional[bool] = None
    'Пропустить проверку минимальной цены.\r\nТолько для выгрузок, при ручной подаче игнорируем.'
    terms: Optional[List[PublishTerm]] = None
    """Условия размещения"""
