# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-cian-announcementapi`

cian-codegen version: 1.5.0

"""
from dataclasses import dataclass
from typing import List, Optional

from cian_enum import NoFormat, StrEnum


class TravelType(StrEnum):
    __value_format__ = NoFormat
    by_car = 'byCar'
    """На автомобиле"""
    by_foot = 'byFoot'
    """Пешком"""


@dataclass
class RailwayInfo:
    """Жд станция"""

    direction_ids: Optional[List[int]] = None
    """Список id направлений, к которым относится станция"""
    distance: Optional[float] = None
    """Расстояние до станции, км"""
    id: Optional[int] = None
    """Id жд станции"""
    name: Optional[str] = None
    """Название"""
    time: Optional[int] = None
    """Время в пути, мин"""
    travel_type: Optional[TravelType] = None
    """Способ передвижения"""
