# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-cian-announcementapi`

cian-codegen version: 1.5.0

"""
from dataclasses import dataclass
from typing import List


@dataclass
class RestoreRequest:
    """Запрос на создание задачи массового восстановления"""

    announcement_ids: List[int]
    """Список id объявлений для восстановления"""
    user_id: int
    """Realty id пользователя"""
