# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-cian-announcementapi`

cian-codegen version: 1.15.0

"""
from dataclasses import dataclass


@dataclass
class SourcePhone:
    country_code: str
    """Код страны"""
    number: str
    """Номер"""
