# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-cian-announcementapi`

cian-codegen version: 1.9.0

"""
from dataclasses import dataclass
from datetime import datetime as _datetime
from typing import Optional

from cian_enum import NoFormat, StrEnum


class Type(StrEnum):
    __value_format__ = NoFormat
    youtube = 'youtube'


@dataclass
class Video:
    """Видео"""

    duration: Optional[int] = None
    """Длительность в секундах"""
    id: Optional[str] = None
    """Id видео"""
    inserted_date: Optional[_datetime] = None
    """Дата вставки видео в объявления"""
    type: Optional[Type] = None
    """Тип видео"""
    upload_date: Optional[_datetime] = None
    """Дата загрузки видео на хостинг"""
    url: Optional[str] = None
    """Ссылка на видео"""
