# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-cian-announcementapi`

cian-codegen version: 1.9.0

"""
from dataclasses import dataclass
from typing import Optional

from cian_enum import NoFormat, StrEnum


class LocationType(StrEnum):
    __value_format__ = NoFormat
    no = 'no'
    """Нет"""
    border = 'border'
    """По границе участка"""
    location = 'location'
    """На участке"""


class Type(StrEnum):
    __value_format__ = NoFormat
    autonomous = 'autonomous'
    """Автономное"""
    central = 'central'
    """Центральное"""
    pumping_station = 'pumpingStation'
    """Водонапорная станция"""
    water_intake_facility = 'waterIntakeFacility'
    """Водозаборный узел"""
    water_tower = 'waterTower'
    """Водонапорная башня"""


@dataclass
class Water:
    """Водоснабжение"""

    capacity: Optional[int] = None
    """Объём, м³/сутки"""
    location_type: Optional[LocationType] = None
    """Локация водоснабжения"""
    possible_to_connect: Optional[bool] = None
    """Возможно подключить"""
    type: Optional[Type] = None
    """Тип водоснабжения"""
