# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-cian-announcementapi`

cian-codegen version: 1.9.0

"""
from dataclasses import dataclass


@dataclass
class WorkTime:
    """Рабочие часы."""

    time_from: str
    """Работает с"""
    time_to: str
    """Работает до"""
