# pylint: skip-file
# isort:skip_file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-cian-ms-announcements`

cian-codegen version: 1.4.1

"""
from .can_update_editdate_result import CanUpdateEditdateResult
from .update_editdate_request import UpdateEditdateRequest
from .update_editdate_result import UpdateEditdateResult
from .v1_can_update_editdate import V1CanUpdateEditdate
