# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-cian-ms-announcements`

cian-codegen version: 1.9.0

"""
from dataclasses import dataclass
from typing import Optional


@dataclass
class ChangedAnnouncement:
    """Изменившиеся объявление"""

    id: int
    """Id объявления"""
    flags: Optional[int] = None
    """Флаги объявления"""
    row_version: Optional[int] = None
    """RowVersion"""
    status: Optional[int] = None
    """Статус объявления"""
