# pylint: skip-file
"""

Code generated by new-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client my-offers`

new-codegen version: 4.0.1

"""
from cian_automation.context import LazyImport

from .clients.public_v1_get_offers import PublicV1GetOffers


class MyOffers(metaclass=LazyImport):
    public_v1_get_offers: PublicV1GetOffers
