# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client search-coverage`

cian-codegen version: 1.4.2

"""
from ._repo import v1_get_offers_search_coverage
