# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-python`

cian-codegen version: 1.15.0

"""
from dataclasses import dataclass
from datetime import date as _date
from typing import Optional


@dataclass
class ChartData:
    date: Optional[_date] = None
    """Дата"""
    value: Optional[int] = None
    """Значание"""
