# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-python`

cian-codegen version: 1.15.0

"""
from dataclasses import dataclass

from cian_enum import NoFormat, StrEnum


class DealType(StrEnum):
    __value_format__ = NoFormat
    rent = 'rent'
    """Аренда"""
    sale = 'sale'
    """Продажа"""


class OfferType(StrEnum):
    __value_format__ = NoFormat
    commercial = 'commercial'
    """коммерческая"""
    flat = 'flat'
    """квартиры"""
    newobject = 'newobject'
    """новостройки"""
    suburban = 'suburban'
    """загородка"""


@dataclass
class CianApiSiteV1GetMyOfferStats:
    deal_type: DealType
    """Тип сделки"""
    id: int
    """Cian id объявление"""
    offer_type: OfferType
    """Тип оффера"""
