# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-python`

cian-codegen version: 1.15.0

"""
from dataclasses import dataclass

from cian_enum import NoFormat, StrEnum

from .my_offers_stats_get_my_offer_stats_response import MyOffersStatsGetMyOfferStatsResponse


class Status(StrEnum):
    __value_format__ = NoFormat
    ok = 'ok'


@dataclass
class GetMyOfferStatsResponse:
    data: MyOffersStatsGetMyOfferStatsResponse
    status: Status
