# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-python`

cian-codegen version: 1.15.0

"""
from dataclasses import dataclass
from typing import Optional

from .period_stats import PeriodStats


@dataclass
class MyOffersStatsGetMyOfferStatsResponse:
    day10: Optional[PeriodStats] = None
    """Статистика за 10 дней"""
    month: Optional[PeriodStats] = None
    """Статистика за месяц"""
