# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-python`

cian-codegen version: 1.15.0

"""
from dataclasses import dataclass
from typing import List, Optional

from .chart_data import ChartData


@dataclass
class PeriodStats:
    avg_position: Optional[float] = None
    """Средняя позициция объявления в результатах поиска за последние сутки"""
    coverage: Optional[float] = None
    """Охват аудитории"""
    favorites: Optional[int] = None
    """Кол-во добавлений в избранное"""
    offer_show: Optional[int] = None
    """Просмотров объявления за период"""
    offer_show_total: Optional[int] = None
    """Просмотров объявления всего"""
    phone_show: Optional[int] = None
    """Просмотров телефона"""
    search_results_selected_chart: Optional[List[ChartData]] = None
    search_results_show: Optional[int] = None
    """Показов в результатах поиска"""
    search_results_show_chart: Optional[List[ChartData]] = None
    show_chart: Optional[List[ChartData]] = None
