# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-python`

cian-codegen version: 1.15.0

"""
from dataclasses import dataclass
from typing import Any, Dict, List, Optional


@dataclass
class SerializeToQueryStringsRequest:
    query_params: Optional[List[Dict[str, Any]]] = None
    """Список параметров поисковых запросов"""
