# pylint: skip-file
# isort:skip_file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client agencies-settings`

cian-codegen version: 1.4.2

"""
from .agency_settings import AgencySettings
from .v1_get_settings import V1GetSettings
