# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client agencies-settings`

cian-codegen version: 1.4.2

"""
from dataclasses import dataclass


@dataclass
class AgencySettings:
    can_sub_agents_edit_offers_from_xml: bool
    """Могут ли сотрдуники редактировать объявления из XML"""
    can_sub_agents_publish_offers: bool
    """Могут ли сотрудники публиковать объявления"""
    can_sub_agents_view_agency_balance: bool
    """Могут ли сотрдники видеть баланс агентства"""
    display_all_agency_offers: bool
    """Показывать ли объявления, оплаченные за личный счет, в моих объявлениях"""
