# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client agencies-settings`

cian-codegen version: 1.4.2

"""
from dataclasses import dataclass


@dataclass
class V1GetSettings:
    agency_id: int
    """ID агентства"""
