# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-cian-announcementapi`

cian-codegen version: 1.4.1

"""
from cian_http.api_client import Api

from . import entities


_api = Api(microservice_name='monolith-cian-announcementapi')
v1_get_announcement = _api.make_client(
    path='/v1/get-announcement/',
    method='GET',
    handle_http_exceptions=True,
    request_schema=entities.V1GetAnnouncement,
    response_schema=entities.ObjectModel,
)
v2_announcements_archive = _api.make_client(
    path='/v2/announcements/archive/',
    method='POST',
    handle_http_exceptions=True,
    request_schema=entities.ArchiveAnnouncementV2Request,
)
