# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-python`

cian-codegen version: 1.4.1

"""
from cian_http.api_client import Api

from . import entities


_api = Api(microservice_name='monolith-python')
internal_api_serialize_query_params = _api.make_client(
    path='/internal_api/serialize-query-params/',
    method='POST',
    handle_http_exceptions=True,
    request_schema=entities.SerializeToQueryStringsRequest,
    response_schema=entities.SerializeToQueryStringsResponse,
)
