# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-python`

cian-codegen version: 1.15.0

"""
from cian_http.api_client import Api

from . import entities


_api = Api(microservice_name='monolith-python')
cian_api_site_v1_get_my_offer_stats = _api.make_client(
    path='/cian-api/site/v1/get-my-offer-stats/',
    method='GET',
    handle_http_exceptions=True,
    request_schema=entities.CianApiSiteV1GetMyOfferStats,
    response_schema=entities.GetMyOfferStatsResponse,
)
internal_api_serialize_query_params = _api.make_client(
    path='/internal_api/serialize-query-params/',
    method='POST',
    handle_http_exceptions=True,
    request_schema=entities.SerializeToQueryStringsRequest,
    response_schema=entities.SerializeToQueryStringsResponse,
)
