# pylint: skip-file
# isort:skip_file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-cian-bill`

cian-codegen version: 1.15.0

"""
from .deactivated_service import DeactivatedService
from .get_deactivated_additional_services_response import GetDeactivatedAdditionalServicesResponse
from .v1_tariffication_get_deactivated_additional_services import V1TarifficationGetDeactivatedAdditionalServices
