# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-cian-bill`

cian-codegen version: 1.9.0

"""
from dataclasses import dataclass
from typing import Optional

from cian_enum import NoFormat, StrEnum


class ServiceType(StrEnum):
    __value_format__ = NoFormat
    free_object = 'FreeObject'
    """Бесплатная публикация"""
    debit_object = 'DebitObject'
    """Платная публикация"""
    premium_object = 'PremiumObject'
    """Премиум публикация"""
    top3 = 'Top3'
    """Тор 3"""
    highlight = 'Highlight'
    """Выделение цветом"""
    calltracking = 'calltracking'
    """Подмена номера, Calltracking, оно же "защита номера\""""
    xml_import = 'XmlImport'
    """Выгрузка объявлений через XML"""
    subscription_for_package = 'SubscriptionForPackage'
    """Абонентская плата за пакет"""
    status_pro = 'StatusPro'
    """Признак статуса ПРО"""
    service_package_activation = 'ServicePackageActivation'
    """Массовый пакет"""
    penalty = 'Penalty'
    """Штрафное списание"""
    order_cancellation = 'OrderCancellation'
    """Отмена платежа"""
    order_transfer = 'OrderTransfer'
    """перенос платежа"""
    tech_spend = 'TechSpend'
    """Произвольное списание"""
    tech_transfer = 'TechTransfer'
    """Перенос произвольной суммы"""
    bonus_payment_expiration = 'BonusPaymentExpiration'
    """Списание истекшего бонусного пополнения"""
    auction = 'auction'
    """Списание за аукцион"""
    demand = 'demand'
    """Списание за заявку на спрос"""
    demand_package = 'demandPackage'
    """Списание за пакет заявок на спрос"""
    cpl_calltracking = 'cplCalltracking'
    """Коллтрекинг по модели CPL"""


@dataclass
class DeactivatedService:
    """Информация об отключённой доп. услуге."""

    announcement_id: int
    """Id объявления."""
    service_type: ServiceType
    """Услуга."""
    auction_bet: Optional[int] = None
    """Ставка аукциона."""
