# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-cian-bill`

cian-codegen version: 1.15.0

"""
from dataclasses import dataclass
from typing import List

from .deactivated_service import DeactivatedService


@dataclass
class GetDeactivatedAdditionalServicesResponse:
    """Ответ со списком отключённых из-за недостатка средств доп. услуг."""
    deactivated_services: List[DeactivatedService]
    """Список отключённых из-за недостатка средств доп. услуг."""
    is_auto_restore_on_payment_enabled: bool
    """У пользователя включено "Возобновление публикации"."""
