# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client search-offers`

cian-codegen version: 1.9.0

"""
from dataclasses import dataclass


@dataclass
class AreaPart:
    area: str
    """Площадь части, м²"""
    price: str
    """Цена части"""
    price_per_meter: str
    """Цена за м²"""
