# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client search-offers`

cian-codegen version: 1.9.0

"""
from dataclasses import dataclass
from typing import List, Optional

from cian_enum import NoFormat, StrEnum


class DealType(StrEnum):
    __value_format__ = NoFormat
    rent = 'rent'
    """Аренда"""
    sale = 'sale'
    """Продажа"""


class OfferType(StrEnum):
    __value_format__ = NoFormat
    commercial = 'commercial'
    """коммерческая"""
    flat = 'flat'
    """квартиры"""
    newobject = 'newobject'
    """новостройки"""
    suburban = 'suburban'
    """загородка"""


@dataclass
class EnrichOffersWithFormattedFieldsRequest:
    offer_ids: List[int]
    """ID офферов"""
    deal_type: Optional[DealType] = None
    """Тип сделки"""
    offer_type: Optional[OfferType] = None
    """Тип объявления"""
