# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client search-offers`

cian-codegen version: 1.9.0

"""
from dataclasses import dataclass
from typing import Optional

from .formatted_fields import FormattedFields


@dataclass
class EnrichOffersWithFormattedFieldsItem:
    fields: Optional[FormattedFields] = None
    """Форматированные поля"""
    id: Optional[int] = None
    """Realty id объявления"""
