# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client search-offers`

cian-codegen version: 1.9.0

"""
from dataclasses import dataclass
from typing import List, Optional

from .area_part import AreaPart


@dataclass
class FormattedFields:
    formatted_additional_extra_info: Optional[str] = None
    """Дополнительная информация с агентской комиссией"""
    formatted_additional_info: Optional[str] = None
    """Дополнительная информация об объекте"""
    formatted_additional_price: Optional[str] = None
    """Дополнительная строка с ценой, например, за квадратный метр"""
    formatted_address: Optional[str] = None
    """Адрес объекта"""
    formatted_area_parts: Optional[List[AreaPart]] = None
    """Части объявления"""
    formatted_card_info: Optional[str] = None
    """Информация об объекте для карточки"""
    formatted_communal_info: Optional[str] = None
    """Информация о коммунальных платежах"""
    formatted_full_info: Optional[str] = None
    """Полная информация об объекте"""
    formatted_full_price: Optional[str] = None
    """Строка с полной ценой"""
    formatted_premises_info: Optional[str] = None
    """Информация о занятости помещения"""
    formatted_price_per_meter: Optional[str] = None
    """Строка с ценой за метр"""
    formatted_short_info: Optional[str] = None
    """Краткая информация об объекте"""
    formatted_short_price: Optional[str] = None
    """Строка с ценой"""
    formatted_vat_type: Optional[str] = None
    """Информация о НДС"""
