# pylint: skip-file
"""

Code generated by new-codegen; DO NOT EDIT.

To re-generate, run `new-codegen generate-client my-offers`

new-codegen version: 4.0.2

"""
from typing import Callable

from cian_automation.web import DecoratedBaseClient

from .. import entities


class PublicV1ActionsUpdateEditDate(DecoratedBaseClient):
    _is_service = True
    microservice_name = 'my-offers'
    path = '/public/v1/actions/update-edit-date/'
    path_args = []
    responses = {'post': entities.OfferActionResponse}
    request_post: Callable[..., 'entities.OfferActionResponse']
