# pylint: skip-file
"""

Code generated by new-codegen; DO NOT EDIT.

To re-generate, run `new-codegen generate-client my-offers`

new-codegen version: 4.0.2

"""
from typing import Callable

from cian_automation.web import DecoratedBaseClient

from .. import entities


class PublicV2GetOffers(DecoratedBaseClient):
    _is_service = True
    microservice_name = 'my-offers'
    path = '/public/v2/get-offers/'
    path_args = []
    responses = {'post': entities.GetOffersV2Response}
    request_post: Callable[..., 'entities.GetOffersV2Response']
