# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client ab-use`

cian-codegen version: 1.7.1

"""
from cian_http.api_client import Api

from . import entities


_api = Api(microservice_name='ab-use')
v1_get_experiment = _api.make_client(
    path='/v1/get-experiment/',
    method='GET',
    handle_http_exceptions=True,
    request_schema=entities.V1GetExperiment,
    response_schema=entities.GetExperimentResponse,
)
