definitions:
  cian_web.schemas.ErrorResponseSchema:
    properties:
      errors:
        items: {title: errors, type: object}
        title: errors
        type: array
      message: {title: message, type: string}
    type: object
  price_estimator.entities.estimation.GetEstimationForRealtorsResponseSchema:
    properties:
      liquidityPeriods: {$ref: '#/definitions/price_estimator.entities.liquidity.LiquidityPeriodsRangeSchema',
        description: Объект с ликвидностью}
      prices: {$ref: '#/definitions/price_estimator.entities.estimation.PriceWithRangeSchema',
        description: Объект с оценкой и её диапазоном}
      url: {description: Ссылка на результаты оценки калькулятора недвижимости, title: url,
        type: string}
    type: object
  price_estimator.entities.estimation.PriceWithRangeSchema:
    properties:
      price: {description: Цена (аренда/продажа) в этом доме(с учётом метража), format: int64,
        title: price, type: integer}
      priceMax: {description: Максимальная цена (аренда/продажа) в этом доме(с учётом
          метража), format: int64, title: price_max, type: integer}
      priceMin: {description: Минимальная цена (аренда/продажа) в этом доме(с учётом
          метража), format: int64, title: price_min, type: integer}
    type: object
  price_estimator.entities.liquidity.LiquidityPeriodsRangeSchema:
    properties:
      periodWithPromotion: {$ref: '#/definitions/price_estimator.entities.liquidity.LiquidityTermRangeSchema',
        description: Срок продажи квартиры "от-до" в днях при текущей цене с продвижением}
      regularPeriod: {$ref: '#/definitions/price_estimator.entities.liquidity.LiquidityTermRangeSchema',
        description: Срок продажи квартиры "от-до" в днях при текущей цене и без продвижения}
    required: [periodWithPromotion, regularPeriod]
    type: object
  price_estimator.entities.liquidity.LiquidityTermRangeSchema:
    properties:
      maxSellingTerm: {description: 'Максимальный срок продажи, в днях', format: int64,
        title: max_selling_term, type: integer}
      minSellingTerm: {description: 'Минимальный срок продажи, в днях', format: int64,
        title: min_selling_term, type: integer}
    required: [minSellingTerm]
    type: object
info: {description: My short description, title: price-estimator, version: 1.0.0}
paths:
  /v2/get-estimation-for-realtors/:
    get:
      parameters:
      - {description: realty ID объявления, in: query, name: realtyOfferId, required: true,
        type: integer}
      produces: [application/json]
      responses:
        '200':
          schema: {$ref: '#/definitions/price_estimator.entities.estimation.GetEstimationForRealtorsResponseSchema'}
        '400':
          schema: {$ref: '#/definitions/cian_web.schemas.ErrorResponseSchema'}
swagger: '2.0'
