# pylint: skip-file
# isort:skip_file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client notification-center`

cian-codegen version: 1.4.3

"""
from .register_notification_v2_request import RegisterNotificationV2Request
from .register_notifications_v2_request import RegisterNotificationsV2Request
