# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client notification-center`

cian-codegen version: 1.4.3

"""
from dataclasses import dataclass
from typing import List

from .mobile_push_settings_parent_item_request import MobilePushSettingsParentItemRequest


@dataclass
class GetMobilePushSettingsResponse:
    items: List[MobilePushSettingsParentItemRequest]
    """Список настроек мобильных пушей"""
