# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client notification-center`

cian-codegen version: 1.4.3

"""
from dataclasses import dataclass

from cian_enum import NoFormat, StrEnum


class OsType(StrEnum):
    __value_format__ = NoFormat
    android = 'android'
    """Android"""
    ios = 'ios'
    """iOS"""


@dataclass
class GetMobilePushSettingsRequest:
    is_authenticated: bool
    """Анонимный/Зарегистрированный пользователь"""
    os_type: OsType
    """Тип операционной системы iOS/Android"""
    user_id: str
    """Идентификатор пользователя"""
