# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client notification-center`

cian-codegen version: 1.4.3

"""
from dataclasses import dataclass
from datetime import datetime
from typing import List, Optional

from cian_enum import NoFormat, StrEnum


class NotificationType(StrEnum):
    __value_format__ = NoFormat
    abandoned_addform = 'abandonedAddform'
    """Напоминание о брошеной форме подачи"""
    chats_many = 'chatsMany'
    """Пуш о новых сообщениях за прошлый день в чате"""
    chats_one = 'chatsOne'
    """Пуш о новом сообщении в чате"""
    cian_services = 'cianServices'
    """Пуши по сервисам и возможностям ЦИАН"""
    deactivated_announcement = 'deactivatedAnnouncement'
    """Истек срок публикации объявления"""
    deal_rent_scoring_completed = 'dealRentScoringCompleted'
    """Пуши об успешном прохождении скоринга арендатором"""
    deal_rent_scoring_failed = 'dealRentScoringFailed'
    """Пуши о проваленном прохождении скоринга арендатором"""
    demand = 'demand'
    """Пуши по спросу"""
    demand_message_package = 'demandMessagePackage'
    """Пуш по пакетам заявок спроса"""
    demand_new = 'demandNew'
    """Новая версия пушей по спросу"""
    favorite_price_changed = 'favoritePriceChanged'
    """Цена изменилась в избранном объявлении"""
    last_search = 'lastSearch'
    """Пуш по последнему поиску"""
    new_profile_for_offer_in_deal = 'newProfileForOfferInDeal'
    """Пуши о новых анкетах для обьявления в сделке"""
    offer_new_duplicate_found = 'offerNewDuplicateFound'
    """Пуш найден новый дубль объявления"""
    offers_favorite_house = 'offersFavoriteHouse'
    """Пуш объявлений в домах из избранного"""
    onbording = 'onbording'
    """Пуши для онбординга-книжки"""
    price_estimator = 'priceEstimator'
    """Пуш об оценке на калькулятор недвижимости"""
    recommended_offers = 'recommendedOffers'
    """Рекомендованные обхявления"""
    review_specialist = 'reviewSpecialist'
    """Оценка специалиста"""
    reviews = 'reviews'
    """Пуш при новой информации в отзывах"""
    rosreestr_check_completed = 'rosreestrCheckCompleted'
    """Закончилась проверка собственника в Росреестре"""
    safe_rent_scoring = 'safeRentScoring'
    """Пуши о прохождении проверки арендатора в безопасной аренде (успешное или неуспешное)"""
    saved_search_new_offer = 'savedSearchNewOffer'
    """Новое объявление в сохраненном поиске"""
    sumsub_check_completed = 'sumsubCheckCompleted'
    """Закончилась проверка пользователя в SumSub"""
    switch_account_type = 'switchAccountType'
    """Смена типа аккаунта"""
    universal_notification = 'universalNotification'
    """Универсальные уведомления"""
    zendesk = 'zendesk'
    """Пуши от zendesk"""


class TransportsToSend(StrEnum):
    __value_format__ = NoFormat
    email = 'email'
    """Email"""
    mailru_notify = 'mailruNotify'
    """ Уведомления в vk и одноклассники """
    mobile_push = 'mobilePush'
    """Мобильный пуш"""
    web_push = 'webPush'
    """Веб пуш"""


@dataclass
class RegisterNotificationV2Request:
    is_authenticated: bool
    """Анонимный/Зарегистрированный пользователь"""
    mobile_push_payload: dict
    """Обязательный параметр, эти данные используются для отображения уведомлений в ЦУ на моб. приложении"""
    notification_type: NotificationType
    """Тип уведомления"""
    text: str
    """Текст уведомления"""
    title: str
    """Название уведомления"""
    user_id: str
    """Идентификатор пользователя"""
    web_url: str
    """Веб ссылка для перехода по уведомлению на вебе"""
    email_payload: Optional[dict] = None
    """Данные для email"""
    entity_id: Optional[int] = None
    """Идентификатор сущности, по которому формируется уведомление"""
    media_url: Optional[str] = None
    """Ссылка на фото в уведомлении"""
    planned_send_datetime: Optional[datetime] = None
    """Желаемое плановое время отправки уведомления"""
    transports_to_send: Optional[List[TransportsToSend]] = None
    """Список транспортов для отправки (по умолчанию - выберутся все доступные у пользователя каналы связи)"""
    web_push_payload: Optional[dict] = None
    """Обязательный параметр, эти данные используются для отображения уведомлений в ЦУ на вебе"""
