# pylint: skip-file
"""

Code generated by new-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client qa-cian-proxy`

new-codegen version: 4.0.0

"""
from dataclasses import dataclass
from typing import List, Optional

from .sub_account import SubAccount


@dataclass
class NewUserResponse:
    email: Optional[str] = None
    """Email."""
    password: Optional[str] = None
    """Пароль."""
    subAccounts: Optional[List[SubAccount]] = None
    userId: Optional[int] = None
    """Id."""
