# pylint: skip-file
"""

Code generated by new-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client qa-cian-proxy`

new-codegen version: 4.0.1

"""
from dataclasses import dataclass
from typing import List, Optional

from cian_enum import NoFormat, StrEnum

from .new_user_params_phone import NewUserParamsPhone


class AgentType(StrEnum):
    __value_format__ = NoFormat
    agency = 'agency'
    """Агентство."""
    specialist = 'specialist'
    """Специалист."""


class PayerType(StrEnum):
    __value_format__ = NoFormat
    legal = 'legal'
    """Юридическое лицо."""
    natural = 'natural'
    """Физическое лицо."""


class Tariff(StrEnum):
    __value_format__ = NoFormat
    base = 'base'
    base_as_part = 'baseAsPart'
    base_old = 'baseOld'
    conscienceless = 'conscienceless'
    emls_virtual_user = 'emlsVirtualUser'
    lider = 'lider'
    no_commerce = 'noCommerce'
    partner = 'partner'
    partner_premium_only = 'partnerPremiumOnly'
    partner_universal_rent = 'partnerUniversalRent'
    partner_universal_sale = 'partnerUniversalSale'
    profi = 'profi'
    profi_as_part = 'profiAsPart'
    region = 'region'
    starter_old = 'starterOld'
    zastroyshik = 'zastroyshik'


class TfaType(StrEnum):
    __value_format__ = NoFormat
    email = 'email'
    """Через email"""
    sms = 'sms'
    """Через sms"""


class UserTrust(StrEnum):
    __value_format__ = NoFormat
    new_user = 'newUser'
    """-1 Ставится при первом добавлении объявления / новый юзер"""
    non_trusted = 'nonTrusted'
    """-2 Установить недоверие / исключен из акции"""
    not_in_stock = 'notInStock'
    """0 Не состоит в акции"""
    party_action = 'partyAction'
    """1 Участник акции «работаем честно»"""
    recidivist = 'recidivist'
    """-3 Рецидивист"""


@dataclass
class NewUserRequest:
    agentType: Optional[AgentType] = None
    """Тип агента."""
    allowCreditOverride: Optional[bool] = None
    """Кредит доступен"""
    allowVasForSub: Optional[bool] = None
    """Разрешить васы для сабагентов"""
    auctionPoints: Optional[float] = None
    """Баллы на аукцион"""
    countryId: Optional[int] = None
    """Идентификатор страны."""
    email: Optional[str] = None
    """Email."""
    emailConfirmed: Optional[bool] = None
    """Email подтвержден."""
    firstName: Optional[str] = None
    """Имя."""
    isIdentified: Optional[bool] = None
    """Флаг идентификации."""
    isMobile: Optional[bool] = None
    """Мобильный пользователь"""
    isPrivateBroker: Optional[bool] = None
    """Частный маклер"""
    isProfessional: Optional[bool] = None
    'Тип пользователя - профессионал, или обычный\r\nЕсли не указан, то будет обычным пользователем (поискуном)'
    isProfileApproved: Optional[bool] = None
    """Подтвержденный профиль"""
    lastName: Optional[str] = None
    """Фамилия."""
    maxAgencySubAccountCount: Optional[int] = None
    """Максимальное количество субагентов в агентстве"""
    money: Optional[float] = None
    """Деньги."""
    password: Optional[str] = None
    """Пароль."""
    payerType: Optional[PayerType] = None
    """Тип плательщика - физическое лицо, юридическое лицо"""
    phone: Optional[str] = None
    """Телефон."""
    phoneConfirmed: Optional[bool] = None
    """Телефон подтвержден."""
    phones: Optional[List[NewUserParamsPhone]] = None
    regionId: Optional[int] = None
    """Идентификатор региона."""
    roles: Optional[List[str]] = None
    """Дополнительные роли пользователя."""
    subAccountCount: Optional[int] = None
    """Количество субагентов. Используется только, когда {Moderation.Enums.AgentAccountType} равен {Moderation.Enums.AgentAccountType.Agency}"""
    tariff: Optional[Tariff] = None
    """Тариф."""
    tfaType: Optional[TfaType] = None
    """Тип двухфакторки"""
    userTrust: Optional[UserTrust] = None
    """Траст, который присвоится пользователю"""
