# pylint: skip-file
"""

Code generated by new-codegen; DO NOT EDIT.

To re-generate, run `new-codegen generate-client qa-cian-proxy`

new-codegen version: 4.0.2

"""
from dataclasses import dataclass
from typing import Optional


@dataclass
class NewUserParamsPhone:
    confirmed: Optional[bool] = None
    """Признак подтвержденности."""
    phone: Optional[str] = None
    """Номер телефона"""
