# pylint: skip-file
# isort:skip_file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client search-coverage`

cian-codegen version: 1.4.2

"""
from .offer_coverage import OfferCoverage
from .offers_coverage_request import OffersCoverageRequest
from .offers_coverage_response import OffersCoverageResponse
