# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client search-coverage`

cian-codegen version: 1.4.2

"""
from dataclasses import dataclass
from datetime import date
from typing import List


@dataclass
class OffersCoverageRequest:
    date_from: date
    """Дата начала периода"""
    date_to: date
    """Дата конца периода"""
    offer_ids: List[int]
    """Id объявлений"""
