# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client search-coverage`

cian-codegen version: 1.4.2

"""
from dataclasses import dataclass


@dataclass
class OfferCoverage:
    coverage: int
    """Охват в процентах"""
    offer_id: int
    """Id объявления"""
    searches_count: int
    """Количество поисков"""
    shows_count: int
    """Количество показов"""
