# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client agents`

cian-codegen version: 1.15.0

"""
from dataclasses import dataclass
from typing import Optional


@dataclass
class AgentBalanceResponse:
    """Баланс сотрудника"""

    auction_points: Optional[float] = None
    """Суммарный баланс неистекших баллов на аукцион"""
    balance: Optional[float] = None
    """Полный суммарный баланс пользователя на текущий момент. Включает все виды денег (бонусы и т.п.)"""
