# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client agents`

cian-codegen version: 1.15.0

"""
from dataclasses import dataclass
from typing import Optional

from .agent_service_packages_limits import AgentServicePackagesLimits


@dataclass
class AgentSpendLimitResponse:
    """Денежный лимит"""

    allow_vas: bool
    """Разрешение на использование VAS"""
    service_packages_limits: AgentServicePackagesLimits
    limit: Optional[float] = None
    """Значение лимита"""
    remaining_balance: Optional[float] = None
    """Остаток лимита"""
