# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client agents`

cian-codegen version: 1.15.1

"""
from dataclasses import dataclass
from typing import List, Optional

from cian_enum import NoFormat, StrEnum

from .agent_balance_response import AgentBalanceResponse
from .agent_phone_response import AgentPhoneResponse
from .agent_spend_limit_response import AgentSpendLimitResponse


class State(StrEnum):
    __value_format__ = NoFormat
    request = 'request'
    """Отправлена заявка на добавление агента к агентству"""
    active = 'active'
    """Активный агент"""
    processing = 'processing'
    """Агент в процессе активации/блокировки"""
    blocked = 'blocked'
    """Заблокированный агент"""
    deleted = 'deleted'
    """Удаленный агент"""
    deleted_and_hidden = 'deletedAndHidden'
    """Удаленный агент"""


@dataclass
class AgentResponse:
    """Сотрудник"""

    phones: List[AgentPhoneResponse]
    """Телефоны сотрудника"""
    state: State
    """Состояния привязки субагентов"""
    user_id: int
    """Id пользователя"""
    balance: Optional[AgentBalanceResponse] = None
    email: Optional[str] = None
    """Адрес email"""
    first_name: Optional[str] = None
    """Имя"""
    last_name: Optional[str] = None
    """Фамилия"""
    limits: Optional[AgentSpendLimitResponse] = None
