# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client agents`

cian-codegen version: 1.15.0

"""
from dataclasses import dataclass
from typing import List


@dataclass
class GetAgenciesWithActivatedStaffServiceResponse:
    """Агентства с активным сервисом Сотрудники"""

    user_ids: List[int]
    """Список RealtyUserIds агентств"""
