# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client agents`

cian-codegen version: 1.15.1

"""
from dataclasses import dataclass
from typing import Optional


@dataclass
class V1GetAgentInfoById:
    agent_id: Optional[int] = None
    """ID агента"""
