from my_offers.services.similars._get_offer_similars import v1_get_offer_similars_public
from my_offers.services.similars._get_offer_similars_desktop import v1_get_offer_similars_desktop_public
from my_offers.services.similars._get_offer_similars_tabs import v1_get_offer_similars_tabs_public
from my_offers.services.similars._get_offers_similars_count import v1_get_offers_similars_count
from my_offers.services.similars._update import update
