# pylint: skip-file
"""

Code generated by new-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client qa-cian-proxy`

new-codegen version: 4.0.1

"""
from cian_automation.context import LazyImport

from .clients.api_qa_v1_new_user import ApiQaV1NewUser


class QaCianProxy(metaclass=LazyImport):
    api_qa_v1_new_user: ApiQaV1NewUser
