definitions:
  cian_web.schemas.ErrorResponseSchema:
    properties:
      errors:
        items:
          title: errors
          type: object
        title: errors
        type: array
      message:
        title: message
        type: string
    type: object
  qa_cian_proxy.repositories.monolith_cian_realty.entities.new_user_params_phone.NewUserParamsPhoneSchema:
    properties:
      confirmed:
        description: Признак подтвержденности.
        title: confirmed
        type: boolean
      phone:
        description: Номер телефона
        title: phone
        type: string
    type: object
  qa_cian_proxy.repositories.monolith_cian_realty.entities.new_user_request.NewUserRequestSchema:
    properties:
      agentType:
        description: Тип агента.
        enum:
        - agency
        - specialist
        type: string
        x-agency: Агентство.
        x-specialist: Специалист.
      allowCreditOverride:
        description: Кредит доступен
        title: allow_credit_override
        type: boolean
      allowVasForSub:
        description: Разрешить васы для сабагентов
        title: allow_vas_for_sub
        type: boolean
      auctionPoints:
        description: Баллы на аукцион
        format: double
        title: auction_points
        type: number
      countryId:
        description: Идентификатор страны.
        format: int64
        title: country_id
        type: integer
      email:
        description: Email.
        title: email
        type: string
      emailConfirmed:
        description: Email подтвержден.
        title: email_confirmed
        type: boolean
      firstName:
        description: Имя.
        title: first_name
        type: string
      isIdentified:
        description: Флаг идентификации.
        title: is_identified
        type: boolean
      isMobile:
        description: Мобильный пользователь
        title: is_mobile
        type: boolean
      isPrivateBroker:
        description: Частный маклер
        title: is_private_broker
        type: boolean
      isProfessional:
        description: "Тип пользователя - профессионал, или обычный\r\nЕсли не указан,\
          \ то будет обычным пользователем (поискуном)"
        title: is_professional
        type: boolean
      isProfileApproved:
        description: Подтвержденный профиль
        title: is_profile_approved
        type: boolean
      lastName:
        description: Фамилия.
        title: last_name
        type: string
      maxAgencySubAccountCount:
        description: Максимальное количество субагентов в агентстве
        format: int64
        title: max_agency_sub_account_count
        type: integer
      money:
        description: Деньги.
        format: double
        title: money
        type: number
      password:
        description: Пароль.
        title: password
        type: string
      payerType:
        description: Тип плательщика - физическое лицо, юридическое лицо
        enum:
        - legal
        - natural
        type: string
        x-legal: Юридическое лицо.
        x-natural: Физическое лицо.
      phone:
        description: Телефон.
        title: phone
        type: string
      phoneConfirmed:
        description: Телефон подтвержден.
        title: phone_confirmed
        type: boolean
      phones:
        items:
          $ref: '#/definitions/qa_cian_proxy.repositories.monolith_cian_realty.entities.new_user_params_phone.NewUserParamsPhoneSchema'
        type: array
      regionId:
        description: Идентификатор региона.
        format: int64
        title: region_id
        type: integer
      roles:
        description: Дополнительные роли пользователя.
        items:
          title: roles
          type: string
        title: roles
        type: array
      subAccountCount:
        description: Количество субагентов. Используется только, когда {Moderation.Enums.AgentAccountType}
          равен {Moderation.Enums.AgentAccountType.Agency}
        format: int64
        title: sub_account_count
        type: integer
      tariff:
        description: Тариф.
        enum:
        - base
        - baseAsPart
        - baseOld
        - conscienceless
        - emlsVirtualUser
        - lider
        - noCommerce
        - partner
        - partnerPremiumOnly
        - partnerUniversalRent
        - partnerUniversalSale
        - profi
        - profiAsPart
        - region
        - starterOld
        - zastroyshik
        type: string
        x-base: ''
        x-baseAsPart: ''
        x-baseOld: ''
        x-conscienceless: ''
        x-emlsVirtualUser: ''
        x-lider: ''
        x-noCommerce: ''
        x-partner: ''
        x-partnerPremiumOnly: ''
        x-partnerUniversalRent: ''
        x-partnerUniversalSale: ''
        x-profi: ''
        x-profiAsPart: ''
        x-region: ''
        x-starterOld: ''
        x-zastroyshik: ''
      tfaType:
        description: Тип двухфакторки
        enum:
        - email
        - sms
        type: string
        x-email: Через email
        x-sms: Через sms
      userTrust:
        description: Траст, который присвоится пользователю
        enum:
        - newUser
        - nonTrusted
        - notInStock
        - partyAction
        - recidivist
        type: string
        x-newUser: -1 Ставится при первом добавлении объявления / новый юзер
        x-nonTrusted: -2 Установить недоверие / исключен из акции
        x-notInStock: 0 Не состоит в акции
        x-partyAction: 1 Участник акции «работаем честно»
        x-recidivist: -3 Рецидивист
    type: object
  qa_cian_proxy.repositories.monolith_cian_realty.entities.new_user_response.NewUserResponseSchema:
    properties:
      email:
        description: Email.
        title: email
        type: string
      password:
        description: Пароль.
        title: password
        type: string
      subAccounts:
        items:
          $ref: '#/definitions/qa_cian_proxy.repositories.monolith_cian_realty.entities.sub_account.SubAccountSchema'
        type: array
      userId:
        description: Id.
        format: int64
        title: user_id
        type: integer
    type: object
  qa_cian_proxy.repositories.monolith_cian_realty.entities.sub_account.SubAccountSchema:
    properties:
      email:
        description: Email.
        title: email
        type: string
      password:
        description: Пароль.
        title: password
        type: string
      userId:
        description: Id.
        format: int64
        title: user_id
        type: integer
    type: object
  qa_cian_proxy.web.schemas.QaNewUserCrestedSchema:
    properties:
      createdUser:
        $ref: '#/definitions/qa_cian_proxy.repositories.monolith_cian_realty.entities.new_user_response.NewUserResponseSchema'
        description: Созданный qa user
      isPrepared:
        description: 'Флаг: создан ли пользователь или взят из базы'
        title: is_prepared
        type: boolean
      phone:
        description: Телефон
        title: phone
        type: string
    required:
    - createdUser
    - isPrepared
    - phone
    type: object
  qa_cian_proxy.web.schemas.QaNewUserSchema:
    properties:
      createNew:
        description: 'Флаг: создвать ли нового пользователя'
        title: create_new
        type: boolean
      user:
        $ref: '#/definitions/qa_cian_proxy.repositories.monolith_cian_realty.entities.new_user_request.NewUserRequestSchema'
        description: Параметры qa user
    required:
    - user
    type: object
info:
  description: qa-cian-proxy
  title: qa-cian-proxy
  version: 1.0.0
paths:
  /api/qa/v1/new-user/:
    post:
      parameters:
      - in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/qa_cian_proxy.web.schemas.QaNewUserSchema'
      produces:
      - application/json
      responses:
        '200':
          schema:
            $ref: '#/definitions/qa_cian_proxy.web.schemas.QaNewUserCrestedSchema'
        '400':
          schema:
            $ref: '#/definitions/cian_web.schemas.ErrorResponseSchema'
swagger: '2.0'
