# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-cian-bill`

cian-codegen version: 1.9.0

"""
from ._repo import v1_tariffication_get_deactivated_additional_services
