# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client newbuilding-search`

cian-codegen version: 1.4.1

"""
from cian_http.api_client import Api

from . import entities


_api = Api(microservice_name='newbuilding-search')
v1_get_newbuildings_by_ids = _api.make_client(
    path='/v1/get-newbuildings-by-ids/',
    method='POST',
    handle_http_exceptions=True,
    request_schema=entities.GetNewBuildingsByIdsRequest,
    response_schema=entities.GetNewBuildingsByIdsResponse,
)
