# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client auction`

cian-codegen version: 1.9.0

"""
from ._repo import v1_get_announcements_info_for_mobile, v1_get_bets_by_announcements
