# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client auction`

cian-codegen version: 1.4.3

"""
from cian_http.api_client import Api

from . import entities


_api = Api(microservice_name='auction')
v1_get_bets_by_announcements = _api.make_client(
    path='/v1/get-bets-by-announcements',
    method='POST',
    handle_http_exceptions=True,
    request_schema=entities.GetAnnouncementsBetsRequest,
    response_schema=entities.AnnouncementsBetResponse,
)
