# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client monolith-cian-ms-announcements`

cian-codegen version: 1.4.1

"""
from ._repo import v1_can_update_editdate, v1_get_changed_announcements_ids, v1_update_editdate
