# pylint: skip-file
# isort:skip_file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client newbuilding-search`

cian-codegen version: 1.4.1

"""
from .get_new_buildings_by_ids_request import GetNewBuildingsByIdsRequest
from .get_newbuilding_by_ids_geo_item import GetNewbuildingByIdsGeoItem
from .get_newbuilding_by_ids_geo import GetNewbuildingByIdsGeo
from .get_newbuilding_by_ids_item import GetNewbuildingByIdsItem
from .get_new_buildings_by_ids_response import GetNewBuildingsByIdsResponse
