# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client newbuilding-search`

cian-codegen version: 1.4.1

"""
from dataclasses import dataclass
from typing import Optional

from .get_newbuilding_by_ids_geo import GetNewbuildingByIdsGeo


@dataclass
class GetNewbuildingByIdsItem:
    full_address: Optional[str] = None
    """Полный адрес ЖК в виде строки"""
    geo: Optional[GetNewbuildingByIdsGeo] = None
    """Информация для гео ЖК"""
    id: Optional[int] = None
    """Id ЖК"""
    name: Optional[str] = None
    """Название ЖК"""
    url: Optional[str] = None
    """Относительный url ЖК"""
