# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client newbuilding-search`

cian-codegen version: 1.4.1

"""
from dataclasses import dataclass
from typing import Optional

from cian_enum import NoFormat, StrEnum


class Type(StrEnum):
    __value_format__ = NoFormat
    country = 'country'
    """Страна"""
    district = 'district'
    """Район"""
    house = 'house'
    """Дом"""
    location = 'location'
    """Местоположение"""
    road = 'road'
    """Шоссе"""
    street = 'street'
    """Улица"""
    underground = 'underground'
    """Метро"""


@dataclass
class GetNewbuildingByIdsGeoItem:
    id: Optional[int] = None
    """Id гео-объекта"""
    type: Optional[Type] = None
    """Тип гео-объекта"""
