# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client newbuilding-search`

cian-codegen version: 1.4.1

"""
from dataclasses import dataclass
from typing import List


@dataclass
class GetNewBuildingsByIdsRequest:
    ids: List[int]
    """Список Ids ЖК"""
