# pylint: skip-file
"""

Code generated by new-codegen; DO NOT EDIT.

To re-generate, run `new-codegen generate-client announcementapi`

new-codegen version: 4.0.2

"""
from dataclasses import dataclass
from typing import Optional

from cian_enum import NoFormat, StrEnum


class Type(StrEnum):
    __value_format__ = NoFormat
    country = 'country'
    """Страна"""
    district = 'district'
    """Район"""
    house = 'house'
    """Дом"""
    location = 'location'
    """Местоположение"""
    road = 'road'
    """Шоссе"""
    street = 'street'
    """Улица"""
    underground = 'underground'
    """Метро"""


@dataclass
class AddressInfo:
    """Адрес"""

    fullName: Optional[str] = None
    """Полное название"""
    id: Optional[int] = None
    """ID гео-привязки"""
    isFormingAddress: Optional[bool] = None
    """Участвует в образовании адреса"""
    locationTypeId: Optional[int] = None
    """ID типа субъекта"""
    name: Optional[str] = None
    """Название"""
    shortName: Optional[str] = None
    """Короткое название"""
    type: Optional[Type] = None
    """Тип гео-привязки"""
