# pylint: skip-file
"""

Code generated by new-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client announcementapi`

new-codegen version: 4.0.0

"""
from dataclasses import dataclass
from typing import Optional

from cian_enum import NoFormat, StrEnum


class Currency(StrEnum):
    __value_format__ = NoFormat
    eur = 'eur'
    """Евро"""
    rur = 'rur'
    """Рубль"""
    usd = 'usd'
    """Доллар"""


class PaymentType(StrEnum):
    __value_format__ = NoFormat
    percent = 'percent'
    """Процент"""
    fixed = 'fixed'
    """Фиксированный"""


@dataclass
class AgentBonus:
    """Бонус агенту."""

    currency: Optional[Currency] = None
    """Валюта. Указывается при фиксированном типе оплаты"""
    paymentType: Optional[PaymentType] = None
    """Тип оплаты"""
    value: Optional[float] = None
    """Значение"""
