# pylint: skip-file
"""

Code generated by new-codegen; DO NOT EDIT.

To re-generate, run `new-codegen generate-client announcementapi`

new-codegen version: 4.0.2

"""
from dataclasses import dataclass
from typing import List, Optional

from cian_enum import NoFormat, StrEnum

from .agent_bonus import AgentBonus
from .utilities_terms import UtilitiesTerms


class ContractType(StrEnum):
    __value_format__ = NoFormat
    lease_assignment = 'leaseAssignment'
    """Переуступка прав аренды"""
    sale = 'sale'
    """Продажа"""


class Currency(StrEnum):
    __value_format__ = NoFormat
    eur = 'eur'
    """Евро"""
    rur = 'rur'
    """Рубль"""
    usd = 'usd'
    """Доллар"""


class IncludedOptions(StrEnum):
    __value_format__ = NoFormat
    operational_costs = 'operationalCosts'
    utility_charges = 'utilityCharges'


class LeaseTermType(StrEnum):
    __value_format__ = NoFormat
    few_months = 'fewMonths'
    """На несколько месяцев"""
    long_term = 'longTerm'
    """Длительный"""


class LeaseType(StrEnum):
    __value_format__ = NoFormat
    direct = 'direct'
    """Прямая аренда"""
    joint_venture = 'jointVenture'
    """Договор совместной деятельности"""
    sublease = 'sublease'
    """Субаренда"""


class PaymentPeriod(StrEnum):
    __value_format__ = NoFormat
    annual = 'annual'
    """За год"""
    monthly = 'monthly'
    """За месяц"""


class PriceType(StrEnum):
    __value_format__ = NoFormat
    all = 'all'
    """Цена за все"""
    square_meter = 'squareMeter'
    """Цена за квадратный метр"""
    sotka = 'sotka'
    """Сотка"""
    hectare = 'hectare'
    """Гектар"""


class SaleType(StrEnum):
    __value_format__ = NoFormat
    alternative = 'alternative'
    """Альтернатива"""
    dupt = 'dupt'
    """Договор уступки права требования"""
    dzhsk = 'dzhsk'
    """Договор ЖСК"""
    free = 'free'
    """Свободная продажа"""
    fz214 = 'fz214'
    """214-ФЗ"""
    investment = 'investment'
    """Договор инвестирования"""
    pdkp = 'pdkp'
    """Предварительный договор купли-продажи"""


class TenantsType(StrEnum):
    __value_format__ = NoFormat
    any = 'any'
    """Любой"""
    family = 'family'
    """Семья"""
    female = 'female'
    """Женщина"""
    male = 'male'
    """Мужчина"""


class VatType(StrEnum):
    __value_format__ = NoFormat
    included = 'included'
    """НДС включен"""
    not_included = 'notIncluded'
    """НДС не включен"""
    vat_included = 'vatIncluded'
    """НДС включен"""
    vat_not_included = 'vatNotIncluded'
    """НДС не включен"""
    usn = 'usn'
    """УСН (упрощенная система налогообложения)"""


@dataclass
class BargainTerms:
    price: float
    """Цена"""
    actionId: Optional[str] = None
    'Значение string.<br />\r\nВы можете добавить акцию, которая идет в вашем ЖК. Для этого вам необходимо обратиться к вашему курирующему менеджеру.\r\nId акции не ставится произвольно, вам его высылает менеджер.'
    agentBonus: Optional[AgentBonus] = None
    """Бонус агенту"""
    agentFee: Optional[int] = None
    """Комиссия от другого агента, %%. По умолчанию 100%."""
    bargainAllowed: Optional[bool] = None
    """Возможен торг"""
    bargainConditions: Optional[str] = None
    """Условия торга"""
    bargainPrice: Optional[float] = None
    """Цена с учетом торга"""
    clientFee: Optional[int] = None
    """Комиссия от прямого клиента, %%. По умолчанию 100%."""
    contractType: Optional[ContractType] = None
    """Тип договора"""
    currency: Optional[Currency] = None
    """Валюта"""
    deposit: Optional[int] = None
    """Залог собственнику"""
    hasGracePeriod: Optional[bool] = None
    """Арендные каникулы"""
    includedOptions: Optional[List[IncludedOptions]] = None
    """Включено в ставку"""
    leaseTermType: Optional[LeaseTermType] = None
    """Срок аренды"""
    leaseType: Optional[LeaseType] = None
    """Тип аренды"""
    minLeaseTerm: Optional[int] = None
    """Минимальный срок аренды, мес"""
    mortgageAllowed: Optional[bool] = None
    """Ипотека"""
    paymentPeriod: Optional[PaymentPeriod] = None
    """Период оплаты"""
    prepayMonths: Optional[int] = None
    """Предоплата, от 1 до 12 месяцев"""
    priceType: Optional[PriceType] = None
    """Тип цены"""
    saleType: Optional[SaleType] = None
    """Тип продажи"""
    securityDeposit: Optional[int] = None
    """Обеспечительный платеж"""
    tenantsType: Optional[TenantsType] = None
    """Состав съемщиков"""
    utilitiesTerms: Optional[UtilitiesTerms] = None
    """Коммунальные услуги"""
    vatIncluded: Optional[bool] = None
    """НДС включен"""
    vatPrice: Optional[float] = None
    vatType: Optional[VatType] = None
