# pylint: skip-file
"""

Code generated by new-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client announcementapi`

new-codegen version: 4.0.1

"""
from dataclasses import dataclass
from typing import Optional


@dataclass
class CommercialBuildingInfrastructure:
    """Инфраструктура"""

    hasAquapark: Optional[bool] = None
    """Аквапарк"""
    hasAtm: Optional[bool] = None
    """Банкомат"""
    hasAutomaticGates: Optional[bool] = None
    """Автоматические ворота"""
    hasBabySitting: Optional[bool] = None
    """Беби-ситинг"""
    hasBankDepartment: Optional[bool] = None
    """Отделение банка"""
    hasBasement: Optional[bool] = None
    """Подвал/погреб"""
    hasBeautyShop: Optional[bool] = None
    """Салон красоты"""
    hasBowling: Optional[bool] = None
    """Боулинг"""
    hasBuffet: Optional[bool] = None
    """Буфет"""
    hasCafe: Optional[bool] = None
    """Кафе"""
    hasCanteen: Optional[bool] = None
    """Столовая"""
    hasCarService: Optional[bool] = None
    """Автосервис"""
    hasCarWash: Optional[bool] = None
    """Автомойка"""
    hasCentralReception: Optional[bool] = None
    """Центральная рецепция"""
    hasCinema: Optional[bool] = None
    """Кинотеатр"""
    hasClothesStudio: Optional[bool] = None
    """Ателье одежды"""
    hasConferenceRoom: Optional[bool] = None
    """Конференц-зал"""
    hasEntryByPass: Optional[bool] = None
    """Въезд по пропускам"""
    hasExhibitionAndWarehouseComplex: Optional[bool] = None
    """Выставочно-складской комплекс"""
    hasFitnessCentre: Optional[bool] = None
    """Фитнес-центр"""
    hasFoodCourt: Optional[bool] = None
    """Фуд-корт"""
    hasGameRoom: Optional[bool] = None
    """Игровая комната"""
    hasHotel: Optional[bool] = None
    """Гостиница"""
    hasHourSecurity: Optional[bool] = None
    """Круглосуточная охрана"""
    hasInspectionPit: Optional[bool] = None
    """Смотровая яма"""
    hasMedicalCenter: Optional[bool] = None
    """Медицинский центр"""
    hasMinimarket: Optional[bool] = None
    """Минимаркет"""
    hasNotaryOffice: Optional[bool] = None
    """Нотариальная контора"""
    hasOfficeSpace: Optional[bool] = None
    """Офисные помещения"""
    hasPark: Optional[bool] = None
    """Парк"""
    hasPharmacy: Optional[bool] = None
    """Аптека"""
    hasPool: Optional[bool] = None
    """Бассейн"""
    hasRestaurant: Optional[bool] = None
    """Ресторан"""
    hasRink: Optional[bool] = None
    """Каток"""
    hasShoppingArea: Optional[bool] = None
    """Торговая зона"""
    hasSlotMachines: Optional[bool] = None
    """Игровые автоматы"""
    hasStudio: Optional[bool] = None
    """Фотосалон"""
    hasSupermarket: Optional[bool] = None
    """Супермаркет"""
    hasTire: Optional[bool] = None
    """Шиномонтаж"""
    hasVideoSurveillance: Optional[bool] = None
    """Видеонаблюдение"""
    hasWarehouse: Optional[bool] = None
    """Складские помещения"""
