# pylint: skip-file
"""

Code generated by new-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client announcementapi`

new-codegen version: 4.0.0

"""
from dataclasses import dataclass
from typing import Optional

from cian_enum import NoFormat, StrEnum


class PersonType(StrEnum):
    __value_format__ = NoFormat
    natural = 'natural'
    """Физическое лицо"""
    legal = 'legal'
    """Юридическое лицо"""


@dataclass
class CplModeration:
    """Информация о CPL модерации"""

    firstName: Optional[str] = None
    """Имя (для физ. лица)"""
    inn: Optional[str] = None
    """ИНН (для юр. лица)"""
    lastName: Optional[str] = None
    """Фамилия (для физ. лица)"""
    personType: Optional[PersonType] = None
    """Тип лица"""
    secondName: Optional[str] = None
    """Отчество (для физ. лица)"""
