# pylint: skip-file
"""

Code generated by new-codegen; DO NOT EDIT.

To re-generate, run `new-codegen generate-client announcementapi`

new-codegen version: 4.0.2

"""
from dataclasses import dataclass
from typing import Optional


@dataclass
class DealRentData:
    """Данные по сделке в аренде, передаваемые при публикации объявления"""

    applyDealRent: Optional[bool] = None
    """Пользователь выбрал галку на подключение услуги "Безопасная аренда\""""
