# pylint: skip-file
"""

Code generated by new-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client announcementapi`

new-codegen version: 4.0.0

"""
from dataclasses import dataclass
from typing import Optional


@dataclass
class Developer:
    """Застройщик"""

    id: Optional[int] = None
    """ID застройщика"""
    name: Optional[str] = None
    """Название"""
