# pylint: skip-file
"""

Code generated by new-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client announcementapi`

new-codegen version: 4.0.1

"""
from dataclasses import dataclass
from typing import Optional

from cian_enum import NoFormat, StrEnum


class GarageType(StrEnum):
    __value_format__ = NoFormat
    built_in = 'builtIn'
    """Встроенный"""
    capital = 'capital'
    """Капитальный"""
    samostroy = 'samostroy'
    """Самострой"""
    shell = 'shell'
    """Ракушка"""


class Material(StrEnum):
    __value_format__ = NoFormat
    brick = 'brick'
    """Кирпичный"""
    metal = 'metal'
    """Металлический"""


class Status(StrEnum):
    __value_format__ = NoFormat
    by_proxy = 'byProxy'
    """По доверенности"""
    cooperative = 'cooperative'
    """Кооператив"""
    ownership = 'ownership'
    """Собственность"""


class Type(StrEnum):
    __value_format__ = NoFormat
    box = 'box'
    """Бокс"""
    garage = 'garage'
    """Гараж"""
    parking_place = 'parkingPlace'
    """Машиноместо"""


@dataclass
class Garage:
    """Гараж"""

    garageType: Optional[GarageType] = None
    """Тип гаража"""
    material: Optional[Material] = None
    """Тип бокса"""
    status: Optional[Status] = None
    """Статус"""
    type: Optional[Type] = None
    """Тип"""
