# pylint: skip-file
"""

Code generated by new-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client announcementapi`

new-codegen version: 4.0.1

"""
from dataclasses import dataclass
from typing import Optional

from cian_enum import NoFormat, StrEnum


class LocationType(StrEnum):
    __value_format__ = NoFormat
    no = 'no'
    """Нет"""
    border = 'border'
    """По границе участка"""
    location = 'location'
    """На участке"""


class PressureType(StrEnum):
    __value_format__ = NoFormat
    high = 'high'
    """Высокое"""
    middle = 'middle'
    """Среднее"""
    low = 'low'
    """Низкое"""


@dataclass
class Gas:
    """Газоснабжение"""

    capacity: Optional[int] = None
    """Ёмкость, м³/час"""
    locationType: Optional[LocationType] = None
    """Локация газоснабжения"""
    possibleToConnect: Optional[bool] = None
    """Возможно подключить"""
    pressureType: Optional[PressureType] = None
    """Давление"""
