# pylint: skip-file
"""

Code generated by new-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client announcementapi`

new-codegen version: 4.0.1

"""
from dataclasses import dataclass
from typing import List, Optional

from .address_info import AddressInfo
from .calculated_undergrounds import CalculatedUndergrounds
from .coordinates import Coordinates
from .district_info import DistrictInfo
from .highway_info import HighwayInfo
from .jk import Jk
from .location_path import LocationPath
from .railway_info import RailwayInfo
from .underground_info import UndergroundInfo


@dataclass
class Geo:
    address: Optional[List[AddressInfo]] = None
    """Адресный элемент"""
    buildingAddress: Optional[str] = None
    """Строительный адрес"""
    calculatedUndergrounds: Optional[List[CalculatedUndergrounds]] = None
    """Автоматически рассчитанное время в пути до метро"""
    coordinates: Optional[Coordinates] = None
    """Координаты точки (пользовательского пина на карте)"""
    countryId: Optional[int] = None
    """ID страны"""
    district: Optional[List[DistrictInfo]] = None
    """Район"""
    highways: Optional[List[HighwayInfo]] = None
    """Шоссе"""
    jk: Optional[Jk] = None
    """ЖК"""
    locationPath: Optional[LocationPath] = None
    """LocationPath"""
    publishCoordinates: Optional[Coordinates] = None
    """Координаты, в которых опубликовано объявление."""
    railways: Optional[List[RailwayInfo]] = None
    """Жд станции"""
    undergrounds: Optional[List[UndergroundInfo]] = None
    """Метро"""
    userInput: Optional[str] = None
    """Адресная строка, введенная пользователем"""
