# pylint: skip-file
"""

Code generated by new-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client announcementapi`

new-codegen version: 4.0.0

"""
from dataclasses import dataclass
from typing import Optional


@dataclass
class HighwayInfo:
    distance: Optional[float] = None
    """Расстояние до города, км"""
    id: Optional[int] = None
    """<a href="http://www.cian.ru/highways.xml" target="_blank">ID шоссе</a>"""
    isDefault: Optional[bool] = None
    """Признак основного шоссе (если указано несколько)"""
    name: Optional[str] = None
    """Название"""
