# pylint: skip-file
"""

Code generated by new-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client announcementapi`

new-codegen version: 4.0.1

"""
from dataclasses import dataclass
from typing import Optional

from cian_enum import NoFormat, StrEnum


class AreaUnitType(StrEnum):
    __value_format__ = NoFormat
    hectare = 'hectare'
    """Гектар"""
    sotka = 'sotka'
    """Сотка"""


class Status(StrEnum):
    __value_format__ = NoFormat
    farm = 'farm'
    """Фермерское хозяйство"""
    private_farm = 'privateFarm'
    """Личное подсобное хозяйство"""
    for_agricultural_purposes = 'forAgriculturalPurposes'
    """Участок сельскохозяйственного назначения"""
    forest_area = 'forestArea'
    """Участок лесного фонда"""
    gardening = 'gardening'
    """Садоводство"""
    gardening_non_profit_partnership = 'gardeningNonProfitPartnership'
    """Садовое некоммерческое товарищество"""
    individual_housing_construction = 'individualHousingConstruction'
    """Индивидуальное жилищное строительство"""
    industrial_land = 'industrialLand'
    """Земля промышленного назначения"""
    industry_transport_communications = 'industryTransportCommunications'
    """Участок промышленности, транспорта, связи и иного не сельхоз. назначения"""
    investment_project = 'investmentProject'
    """Инвестпроект"""
    of_protected_categories = 'ofProtectedCategories'
    """Особо охраняемых категорий"""
    reserve = 'reserve'
    """Участок запаса"""
    suburban_non_profit_partnership = 'suburbanNonProfitPartnership'
    """Дачное некоммерческое партнерство"""
    suburban_non_profit_settlements_partnership = 'suburbanNonProfitSettlementsPartnership'
    """Дачное некоммерческое партнерство поселений"""
    water_area = 'waterArea'
    """Участок водного фонда"""
    settlements = 'settlements'
    """Поселений"""


class Type(StrEnum):
    __value_format__ = NoFormat
    owned = 'owned'
    """В собственности"""
    rent = 'rent'
    """В аренде"""


@dataclass
class Land:
    area: Optional[float] = None
    """Площадь участка"""
    areaUnitType: Optional[AreaUnitType] = None
    """Единица измерения"""
    possibleToChangeStatus: Optional[bool] = None
    """Возможно изменить статус"""
    status: Optional[Status] = None
    """Категория земли"""
    type: Optional[Type] = None
    """Тип участка"""
