# pylint: skip-file
"""

Code generated by new-codegen; DO NOT EDIT.

To re-generate, run `new-codegen generate-client announcementapi`

new-codegen version: 4.0.2

"""
from dataclasses import dataclass
from typing import Optional

from cian_enum import NoFormat, StrEnum


class Type(StrEnum):
    __value_format__ = NoFormat
    cargo = 'cargo'
    """Грузовой"""
    escalator = 'escalator'
    """Эскалатор"""
    lift = 'lift'
    """Лифт"""
    passenger = 'passenger'
    """Пассажирский"""
    telpher = 'telpher'
    """Тельфер"""
    travelator = 'travelator'
    """Траволатор"""


@dataclass
class LiftType:
    """Лифты"""

    additionalType: Optional[str] = None
    """Дополнительный тип"""
    count: Optional[int] = None
    """Количество"""
    loadCapacity: Optional[float] = None
    """Грузоподъёмность"""
    type: Optional[Type] = None
    """Тип лифта"""
