# pylint: skip-file
"""

Code generated by new-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client announcementapi`

new-codegen version: 4.0.0

"""
from dataclasses import dataclass
from typing import List, Optional


@dataclass
class LocationPath:
    """LocationPath"""

    childToParent: Optional[List[int]] = None
    """Список локаций отсортированный от более детализированного к региону"""
    countryId: Optional[int] = None
    """ID страны"""
