# pylint: skip-file
"""

Code generated by new-codegen; DO NOT EDIT.

To re-generate, run `new-codegen generate-client announcementapi`

new-codegen version: 4.0.2

"""
from dataclasses import dataclass
from typing import Optional

from cian_enum import NoFormat, StrEnum


class Currency(StrEnum):
    __value_format__ = NoFormat
    eur = 'eur'
    """Евро"""
    rur = 'rur'
    """Рубль"""
    usd = 'usd'
    """Доллар"""


class LocationType(StrEnum):
    __value_format__ = NoFormat
    external = 'external'
    """За территорией объекта"""
    internal = 'internal'
    """На территории объекта"""


class PurposeType(StrEnum):
    __value_format__ = NoFormat
    cargo = 'cargo'
    """Для грузового транспорта"""
    passenger = 'passenger'
    """Для легковесного транспорта"""


class Type(StrEnum):
    __value_format__ = NoFormat
    ground = 'ground'
    """Наземная"""
    multilevel = 'multilevel'
    """Многоуровневая"""
    roof = 'roof'
    """На крыше"""
    underground = 'underground'
    """Подземная"""
    open = 'open'
    """Открытая"""


@dataclass
class Parking:
    """Парковка"""

    currency: Optional[Currency] = None
    """Валюта"""
    isAvailable: Optional[bool] = None
    """Доступна"""
    isFree: Optional[bool] = None
    """Бесплатная"""
    locationType: Optional[LocationType] = None
    """Расположение парковки"""
    placesCount: Optional[int] = None
    """Количество мест"""
    priceEntry: Optional[float] = None
    """Стоимость въезда"""
    priceMonthly: Optional[float] = None
    """Стоимость в месяц за место"""
    purposeType: Optional[PurposeType] = None
    """Назначение парковки"""
    type: Optional[Type] = None
    """Тип парковки"""
