# pylint: skip-file
"""

Code generated by new-codegen; DO NOT EDIT.

To re-generate, run `new-codegen generate-client announcementapi`

new-codegen version: 4.0.2

"""
from dataclasses import dataclass
from typing import Optional

from cian_enum import NoFormat, StrEnum

from .coordinates import Coordinates


class Source(StrEnum):
    __value_format__ = NoFormat
    camera = 'camera'
    """Снимок с камеры."""
    gallery = 'gallery'
    """Выбрано из галереи."""


@dataclass
class Photo:
    coordinates: Optional[Coordinates] = None
    """Координаты снимка."""
    fullUrl: Optional[str] = None
    """URL исходного изображения"""
    id: Optional[int] = None
    """ID фотографии"""
    isDefault: Optional[bool] = None
    """Является ли фото по-умолчанию"""
    miniUrl: Optional[str] = None
    """URL превью"""
    rotateDegree: Optional[int] = None
    """Угол поворота"""
    source: Optional[Source] = None
    """Источник фото."""
    thumbnail2Url: Optional[str] = None
    """URL превью для мобильных приложений"""
    thumbnailUrl: Optional[str] = None
    """URL превью"""
