# pylint: skip-file
"""

Code generated by new-codegen; DO NOT EDIT.

To re-generate, run `new-codegen generate-client announcementapi`

new-codegen version: 4.0.2

"""
from dataclasses import dataclass
from typing import List, Optional

from .publish_term import PublishTerm


@dataclass
class PublishTerms:
    """Условия размещения объявления"""

    autoprolong: Optional[bool] = None
    """Автопродление включено"""
    infinitePublishPeriod: Optional[bool] = None
    'Если true, то будет использован бесконечный период публикации.\r\nТолько для выгрузок, при ручной подаче игнорируем.'
    skipBilling: Optional[bool] = None
    'Пропускает биллинг объявления.\r\nТолько для выгрузок, при ручной подаче игнорируем.'
    skipMinimalPriceCheck: Optional[bool] = None
    'Пропустить проверку минимальной цены.\r\nТолько для выгрузок, при ручной подаче игнорируем.'
    terms: Optional[List[PublishTerm]] = None
    """Условия размещения"""
