# pylint: skip-file
"""

Code generated by new-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client announcementapi`

new-codegen version: 4.0.1

"""
from dataclasses import dataclass
from typing import List, Optional

from cian_enum import NoFormat, StrEnum


class TravelType(StrEnum):
    __value_format__ = NoFormat
    by_car = 'byCar'
    """На автомобиле"""
    by_foot = 'byFoot'
    """Пешком"""


@dataclass
class RailwayInfo:
    """Жд станция"""

    directionIds: Optional[List[int]] = None
    """Список id направлений, к которым относится станция"""
    distance: Optional[float] = None
    """Расстояние до станции, км"""
    id: Optional[int] = None
    """Id жд станции"""
    name: Optional[str] = None
    """Название"""
    time: Optional[int] = None
    """Время в пути, мин"""
    travelType: Optional[TravelType] = None
    """Способ передвижения"""
