# pylint: skip-file
"""

Code generated by new-codegen; DO NOT EDIT.

To re-generate, run `new-codegen generate-client announcementapi`

new-codegen version: 4.0.2

"""
from dataclasses import dataclass
from typing import Optional


@dataclass
class RentByParts:
    """Класс для представления части помещения в аренду"""

    area: Optional[float] = None
    """Площадь части"""
    price: Optional[float] = None
    """Стоимость части"""
