# pylint: skip-file
"""

Code generated by new-codegen; DO NOT EDIT.

To re-generate, run `new-codegen generate-client announcementapi`

new-codegen version: 4.0.2

"""
from dataclasses import dataclass
from typing import Optional


@dataclass
class SelfEmployed:
    """Данные о статусе самозанятости пользователя"""

    inn: Optional[str] = None
    'ИНН пользователя <br />\r\nЕсли пришло null - значит пользователь стёр свой ИНН'
