# pylint: skip-file
"""

Code generated by new-codegen; DO NOT EDIT.

To re-generate, run `new-codegen generate-client announcementapi`

new-codegen version: 4.0.2

"""
from dataclasses import dataclass


@dataclass
class SourcePhone:
    countryCode: str
    """Код страны"""
    number: str
    """Номер"""
