# pylint: skip-file
"""

Code generated by new-codegen; DO NOT EDIT.

To re-generate, run `new-codegen generate-client announcementapi`

new-codegen version: 4.0.2

"""
from dataclasses import dataclass
from typing import Optional

from cian_enum import NoFormat, StrEnum


class TariffGridType(StrEnum):
    __value_format__ = NoFormat
    package_tariff = 'packageTariff'
    """Тарифная сетка на основе пакетов и таблицы Tariff"""
    service_package_group = 'servicePackageGroup'
    'Покупка по слоту\r\nTariffAction для таких теперь создается, но не списывается'
    service_package = 'servicePackage'
    """Покупка по пакету"""
    dynamic_pricing = 'dynamicPricing'
    """Произвольное ценообразование"""


@dataclass
class TariffIdentificator:
    """Идентификатор записи в тарифной сетке."""

    tariffGridType: Optional[TariffGridType] = None
    tariffId: Optional[int] = None
