# pylint: skip-file
"""

Code generated by new-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client announcementapi`

new-codegen version: 4.0.0

"""
from dataclasses import dataclass
from typing import Optional

from cian_enum import NoFormat, StrEnum


class TransportType(StrEnum):
    __value_format__ = NoFormat
    transport = 'transport'
    """На транспорте"""
    walk = 'walk'
    """Пешком"""


@dataclass
class UndergroundInfo:
    cianId: Optional[int] = None
    """ID линии метро на ЦИАНе"""
    id: Optional[int] = None
    """<a href="http://www.cian.ru/metros-moscow.xml" target="_blank">ID метро в Москве</a> (Int32)<br /><a href="http://www.cian.ru/metros-petersburg.xml" target="_blank">ID метро в Санкт-Петербурге</a> (Int32)<br /><a href="http://www.cian.ru/metros-samara.xml" target="_blank">ID метро в Самаре</a> (Int32)<br /><a href="http://www.cian.ru/metros-nn.xml" target="_blank">ID метро в Нижнем Новгороде</a> (Int32)<br /><a href="http://www.cian.ru/metros-novosibirsk.xml" target="_blank">ID метро в Новосибирске</a> (Int32)<br /><a href="http://www.cian.ru/metros-kazan.xml" target="_blank">ID метро в Казани</a> (Int32)<br /><a href="http://www.cian.ru/metros-ekaterinburg.xml" target="_blank">ID метро в Екатеринбурге</a>"""
    isDefault: Optional[bool] = None
    """Признак основной станции метро (если указано несколько)"""
    lineColor: Optional[str] = None
    """Цвет линии метро, hex"""
    lineId: Optional[int] = None
    """ID линии метро"""
    name: Optional[str] = None
    """Название"""
    time: Optional[int] = None
    """Время в пути в минутах до метро, мин"""
    transportType: Optional[TransportType] = None
    """Способ передвижения до метро"""
