# pylint: skip-file
"""

Code generated by new-codegen; DO NOT EDIT.

To re-generate, run `new-codegen generate-client announcementapi`

new-codegen version: 4.0.2

"""
from dataclasses import dataclass
from typing import Optional

from .self_employed import SelfEmployed


@dataclass
class UserData:
    """Данные о пользователе, передаваемые при публикации объявления"""

    selfEmployedData: Optional[SelfEmployed] = None
    """Данные о статусе самозанятости пользователя"""
