# pylint: skip-file
"""

Code generated by new-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client announcementapi`

new-codegen version: 4.0.0

"""
from dataclasses import dataclass
from typing import Optional


@dataclass
class UtilitiesTerms:
    """Коммунальные платежи"""

    flowMetersNotIncludedInPrice: Optional[bool] = None
    """Счетчики оплачиваются отдельно"""
    includedInPrice: Optional[bool] = None
    """Включены в стоимость"""
    price: Optional[float] = None
    """Сумма платежей"""
