# pylint: skip-file
"""

Code generated by new-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client announcementapi`

new-codegen version: 4.0.0

"""
from dataclasses import dataclass
from datetime import datetime
from typing import Optional

from cian_enum import NoFormat, StrEnum


class Type(StrEnum):
    __value_format__ = NoFormat
    youtube = 'youtube'


@dataclass
class Video:
    """Видео"""

    duration: Optional[int] = None
    """Длительность в секундах"""
    id: Optional[str] = None
    """Id видео"""
    insertedDate: Optional[datetime] = None
    """Дата вставки видео в объявления"""
    type: Optional[Type] = None
    """Тип видео"""
    uploadDate: Optional[datetime] = None
    """Дата загрузки видео на хостинг"""
    url: Optional[str] = None
    """Ссылка на видео"""
