"""

Code generated by cian-testcodegen.

cian-testcodegen version: 3.0.0

"""
from typing import List

from automation_helpers.base import BaseTest
from pytest import mark


@mark.my_offers_exchange
class MyOffersHelper(BaseTest):
    pass
