"""

Code generated by cian-testcodegen.

cian-testcodegen version: 3.0.0

"""
from typing import List

from pytest import mark

from automation_helpers.base import BaseTest


@mark.my_offers
class MyOffersHelper(BaseTest):
    pass
