"""

Code generated by cian-testcodegen.

cian-testcodegen version: 3.0.0

"""
import time
from typing import TYPE_CHECKING

import pytest

from .cian.my_offers.entities import Filter, GetOffersRequest
from .cian.my_offers.entities.filter import StatusTab
from .helper import MyOffersHelper


if TYPE_CHECKING:
    from .cian.services import CianServices


class TestPublicV2GetOffers(MyOffersHelper):
    # todo: https://jira.cian.tech/browse/CD-75751
    @pytest.mark.base
    def test_200_post(self, sl: 'CianServices', context):
        # arrange
        user = self.create_user(sl, 'base', True, 1)
        self.create_offer(sl, user_id=user.userId)

        # ждем появления оффера в my-offers
        time.sleep(10)

        # act
        with context.x_real_user(user_id=user.userId):
            response = sl.my_offers.public_v2_get_offers.request_post(
                data=GetOffersRequest(
                    filters=Filter(
                        dealType=None,
                        hasPhoto=None,
                        isInHiddenBase=None,
                        isManual=None,
                        offerType=None,
                        searchText=None,
                        services=None,
                        statusTab=StatusTab.active,
                        subAgentIds=None,
                    )
                )
            )

        # assert
        assert response is not None
