from my_offers.services.offer_relevance_warnings._get_offer_relevance_warnings import (
    get_offer_relevance_warnings_degradation_handler,
)
from my_offers.services.offer_relevance_warnings._save_offer_relevance_warning import save_offer_relevance_warning
