# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client users`

cian-codegen version: 1.7.1

"""
from cian_http.api_client import Api

from . import entities


_api = Api(microservice_name='users')
v1_get_users = _api.make_client(
    path='/v1/get-users/',
    method='POST',
    handle_http_exceptions=True,
    request_schema=entities.UserIdsRequest,
    response_schema=entities.GetUsersResponse,
)
