# pylint: skip-file
# isort:skip_file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client emails`

cian-codegen version: 1.4.1

"""
from .send_email_by_email_request import SendEmailByEmailRequest
from .send_email_by_email_response_item import SendEmailByEmailResponseItem
from .send_email_by_email_response import SendEmailByEmailResponse
