# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client emails`

cian-codegen version: 1.4.1

"""
from dataclasses import dataclass
from typing import Optional

from cian_enum import NoFormat, StrEnum


class Status(StrEnum):
    __value_format__ = NoFormat
    success = 'success'
    """Сообщение отправлено"""
    user_not_found = 'userNotFound'
    """Не нашли пользователя"""
    already_sent = 'alreadySent'
    """Сообщение было отправлено"""


@dataclass
class SendEmailByEmailResponseItem:
    """Элемент списка отправки письма по Email"""

    email: Optional[str] = None
    """Email пользователя - получателя письма"""
    status: Optional[Status] = None
    """Статус отправки письма"""
