# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client emails`

cian-codegen version: 1.4.1

"""
from dataclasses import dataclass
from typing import List, Optional

from cian_enum import NoFormat, StrEnum

from .send_email_by_email_response_item import SendEmailByEmailResponseItem


class Status(StrEnum):
    __value_format__ = NoFormat
    success = 'success'
    """Сообщение отправлено"""
    user_not_found = 'userNotFound'
    """Не нашли пользователя"""
    already_sent = 'alreadySent'
    """Сообщение было отправлено"""


@dataclass
class SendEmailByEmailResponse:
    """Ответ Апи на отправку письма по Email"""

    items: Optional[List[SendEmailByEmailResponseItem]] = None
    """Список статусов отправленных писем Email-Статус"""
    status: Optional[Status] = None
    """Статус сообщения"""
