# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client search-offers`

cian-codegen version: 1.9.0

"""
from ._repo import v1_enrich_offers_with_formatted_fields
