# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client search-offers`

cian-codegen version: 1.9.0

"""
from cian_http.api_client import Api

from . import entities


_api = Api(microservice_name='search-offers')
v1_enrich_offers_with_formatted_fields = _api.make_client(
    path='/v1/enrich-offers-with-formatted-fields/',
    method='POST',
    handle_http_exceptions=True,
    request_schema=entities.EnrichOffersWithFormattedFieldsRequest,
    response_schema=entities.EnrichOffersWithFormattedFieldsResponse,
)
