# pylint: skip-file
# isort:skip_file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client callbook`

cian-codegen version: 1.9.0

"""
from .get_user_calls_by_offers_stats_request import GetUserCallsByOffersStatsRequest
from .offer_call_count import OfferCallCount
from .get_user_calls_by_offers_totals_response import GetUserCallsByOffersTotalsResponse
