# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client callbook`

cian-codegen version: 1.9.0

"""
from dataclasses import dataclass
from typing import List

from .offer_call_count import OfferCallCount


@dataclass
class GetUserCallsByOffersTotalsResponse:
    data: List[OfferCallCount]
    """Статистика по звонкам за все время по объявлениям"""
