# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client callbook`

cian-codegen version: 1.12.2

"""
from dataclasses import dataclass
from typing import List


@dataclass
class GetUserCallsByOffersStatsRequest:
    offer_ids: List[int]
    """Список id объявлений"""
    user_id: int
    """Id пользователя"""
