# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client callbook`

cian-codegen version: 1.9.0

"""
from dataclasses import dataclass


@dataclass
class OfferCallCount:
    calls_count: int
    """Кол-во звонков"""
    missed_calls_count: int
    """Кол-во пропущенных звонков"""
    offer_id: int
    """Id объявления"""
