# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client moderation`

cian-codegen version: 1.9.0

"""
from dataclasses import dataclass
from typing import List

from .get_video_offence_for_announcement import GetVideoOffenceForAnnouncement


@dataclass
class GetVideoOffencesForAnnouncementsResponse:
    """Нарушения для скрытых видео"""

    items: List[GetVideoOffenceForAnnouncement]
    """Скрытые видео в объявлениях"""
