# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client moderation`

cian-codegen version: 1.9.0

"""
from dataclasses import dataclass
from typing import List, Optional


@dataclass
class GetImageOffenceForAnnouncement:
    """Нарушение для скрытой фотографии"""

    announcement_id: int
    """ID объявления"""
    comment: Optional[str] = None
    """Комментарий"""
    image_ids: Optional[List[int]] = None
    """Список скрытых фотографий"""
    title: Optional[str] = None
    """Заголовок"""
