# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client moderation`

cian-codegen version: 1.9.0

"""
from dataclasses import dataclass
from typing import List, Optional


@dataclass
class GetVideoOffenceForAnnouncement:
    """Нарушение для скрытого видео"""

    announcement_id: int
    """ID объявления"""
    comment: Optional[str] = None
    """Заголовок"""
    title: Optional[str] = None
    """Заголовок"""
    video_ids: Optional[List[str]] = None
    """Список скрытых видео"""
