# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client moderation`

cian-codegen version: 1.9.0

"""
from dataclasses import dataclass
from typing import List

from .get_image_offence_for_announcement import GetImageOffenceForAnnouncement


@dataclass
class GetImageOffencesForAnnouncementsResponse:
    """Нарушения для скрытых фотографий"""

    items: List[GetImageOffenceForAnnouncement]
    """Скрытые фотографии в объявлениях"""
