# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client moderation`

cian-codegen version: 1.9.0

"""
from ._repo import v1_get_image_offences_for_announcements, v1_get_video_offences_for_announcements
