# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client callbook`

cian-codegen version: 1.9.0

"""
from ._repo import v1_get_user_calls_by_offers_totals
