# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client callbook`

cian-codegen version: 1.12.2

"""
from cian_http.api_client import Api

from . import entities


_api = Api(microservice_name='callbook')
v1_get_user_calls_by_offers_totals = _api.make_client(
    path='/v1/get-user-calls-by-offers-totals/',
    method='POST',
    handle_http_exceptions=True,
    request_schema=entities.GetUserCallsByOffersStatsRequest,
    response_schema=entities.GetUserCallsByOffersTotalsResponse,
)
