# pylint: skip-file
"""

Code generated by new-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client qa-cian-proxy`

new-codegen version: 4.0.0

"""
from typing import Callable

from cian_automation.context import LazyImport
from cian_automation.web import DecoratedBaseClient

from .. import entities


class ApiQaV1NewUser(DecoratedBaseClient):
    _is_service = True
    microservice_name = 'qa-cian-proxy'
    path = '/api/qa/v1/new-user/'
    path_args = []
    responses = {'post': entities.QaNewUserCrested}
    request_post: Callable[..., 'entities.QaNewUserCrested']
