# pylint: skip-file
# isort:skip_file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client geo-subdomain`

cian-codegen version: 1.4.1

"""
from .get_subdomains_response import GetSubdomainsResponse
