# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client geo-subdomain`

cian-codegen version: 1.4.1

"""
from dataclasses import dataclass
from typing import List, Optional


@dataclass
class GetSubdomainsResponse:
    subdomains: Optional[List[dict]] = None
    """Список поддоменов"""
