# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client offers-duplicates`

cian-codegen version: 1.4.3

"""
from cian_http.api_client import Api

from . import entities


_api = Api(microservice_name='offers-duplicates')
v1_get_offers_duplicates_by_ids = _api.make_client(
    path='/v1/get-offers-duplicates-by-ids/',
    method='POST',
    handle_http_exceptions=True,
    request_schema=entities.GetOffersDuplicatesByIdsRequest,
    response_schema=entities.GetOffersDuplicatesByIdsResponse,
)
