# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client favorites`

cian-codegen version: 1.9.0

"""
from ._repo import v1_get_offers_favorites_count
