# pylint: skip-file
"""

Code generated by cian-codegen; DO NOT EDIT.

To re-generate, run `codegen generate-client favorites`

cian-codegen version: 1.9.0

"""
from typing import List

from cian_http.api_client import Api

from . import entities


_api = Api(microservice_name='favorites')
v1_get_offers_favorites_count = _api.make_client(
    path='/v1/get-offers-favorites-count/',
    method='POST',
    handle_http_exceptions=True,
    request_schema=List[int],
    response_schema=List[entities.OfferFavoriteCount],
)
