definitions:
  cian_web.schemas.ErrorResponseSchema:
    properties:
      errors:
        items:
          title: errors
          type: object
        title: errors
        type: array
      message:
        title: message
        type: string
    type: object
  favorites.web.entities.offer_favorite.OfferFavoriteCountSchema:
    properties:
      count:
        format: int64
        title: count
        type: integer
      offerId:
        format: int64
        title: offer_id
        type: integer
    required:
    - count
    - offerId
    type: object
info:
  description: Favorites
  title: favorites
  version: 1.0.0
paths:
  /v1/get-offers-favorites-count/:
    post:
      parameters:
      - in: body
        name: body
        required: true
        schema:
          items:
            format: int64
            title: field
            type: integer
          title: field
          type: array
      produces:
      - application/json
      responses:
        '200':
          schema:
            items:
              $ref: '#/definitions/favorites.web.entities.offer_favorite.OfferFavoriteCountSchema'
            type: array
        '400':
          schema:
            $ref: '#/definitions/cian_web.schemas.ErrorResponseSchema'
swagger: '2.0'
x-cian-mq:
  exchanges: {}
  spec-version: '1.0'
